In [1]:
import pandas as pd
import numpy as np

In [2]:
city_data = {
"City": ["New York City", "Paris", "Barcelona", "Rome"],
"Country": ["United States", "France", "Spain", "Italy"],
"Population": [8600000, 2141000, 5515000, 2873000]
}

cities = pd.DataFrame(city_data)
cities

            City        Country  Population
0  New York City  United States     8600000
1          Paris         France     2141000
2      Barcelona          Spain     5515000
3           Rome          Italy     2873000

In [3]:
cities.transpose() #inverteu as colunas e linhas

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

In [4]:
random_data = np.random.randint(1, 101, [3,5])
random_data

array([[ 6, 68, 29, 51, 57],
       [83, 26, 79, 55, 96],
       [33, 35, 85, 29, 58]])

In [5]:
random = pd.DataFrame(random_data)
random

    0   1   2   3   4
0   6  68  29  51  57
1  83  26  79  55  96
2  33  35  85  29  58

In [6]:
row_labels = ['Morning', 'Afternoon', 'Evening']
temperatures = pd.DataFrame(data=random_data, index=row_labels)
temperatures

            0   1   2   3   4
Morning     6  68  29  51  57
Afternoon  83  26  79  55  96
Evening    33  35  85  29  58

In [7]:
column_labels = (
"Monday",
"Tuesday",
"Wednesday",
"Thursday",
"Friday",
)

In [8]:
pd.DataFrame(data=random_data, index=row_labels, columns=column_labels)

           Monday  Tuesday  Wednesday  Thursday  Friday
Morning         6       68         29        51      57
Afternoon      83       26         79        55      96
Evening        33       35         85        29      58

In [9]:
row_labels = ["Morning", "Afternoon", "Morning"]
column_labels = [
"Monday",
"Tuesday",
"Wednesday",
"Tuesday",
"Friday"
]

pd.DataFrame(data=random_data, index=row_labels, columns=column_labels) #O pandas aceita ter índices de rótulos duplicados

           Monday  Tuesday  Wednesday  Tuesday  Friday
Morning         6       68         29       51      57
Afternoon      83       26         79       55      96
Morning        33       35         85       29      58

In [10]:
pd.read_csv('nba.csv')

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [11]:
pd.read_csv('nba.csv', parse_dates=['Birthday']) #Transforma o tipo de dado de string para datetimes

/tmp/ipykernel_28547/2503751441.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('nba.csv', parse_dates=['Birthday']) #Transforma o tipo de dado de string para datetimes

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [12]:
df_nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])

/tmp/ipykernel_28547/879108857.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])

In [13]:
df_nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [14]:
df_nba.index #RangeIndex incue 3 atributos: start(valor mais baixo), stop(valor mais alto), step(intevalo entre todos os valores)

RangeIndex(start=0, stop=450, step=1)

In [15]:
df_nba.columns #os rótulos das colunas

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [16]:
df_nba.ndim #Retorna o número de dimensões do objeto Panda

2

In [17]:
df_nba.shape #Este atributo retorna as dimensões do DataFrame em uma tupla. Ou seja, 450 linhas e 5 colunas

(450, 5)

In [18]:
df_nba.size #Este atributo calcula o número total de valores no grupo de dados. Valores sem sentido como (NaNs) estão inclusos na conta

2250

In [19]:
df_nba.count() #Caso queira excluir os valores sem sentido o método 'count()' retorna uma serie com a quantidade de valores presentes por colunas

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [20]:
df_nba.count().sum() #Foi somado todos os valores das series com o método 'sum()' para obter os números de valores não nulos no DataFrame

np.int64(2250)

In [21]:
data = {
    'A': [1, np.nan],
    'B': [2,3]
}

df = pd.DataFrame(data)
df

     A  B
0  1.0  2
1  NaN  3

In [22]:
df.size #Possui 4 células

4

In [23]:
df.count()

A    1
B    2
dtype: int64

In [24]:
df.count().sum() #Retorna 3 pq das 4 células, 3 possuem valores não nulos

np.int64(3)

In [25]:
#Series e DataFrame possuem métodos em comum como head() e tail()

In [26]:
df_nba.sample(3) #O método sample(n) coleta n números de linhas aleatórias do DataFrame

               Name              Team Position   Birthday    Salary
344  Reggie Bullock   New York Knicks       SF 1991-03-16   4000000
148  Richaun Holmes  Sacramento Kings        C 1993-10-15   4767000
112    Courtney Lee  Dallas Mavericks       SG 1985-10-03  12759670

In [27]:
df_nba.nunique() #no DataFrame o método nunique conta o número de valores únicos presentes nem cada coluna, diferente da serie que este método retorna os valores únicos de toda a serie

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [28]:
df_nba.max() #Diferente da serie que o método 'max()' retorna o valor máximo da serie, no DataFrame este método retorna valor máximo de cada coluna (em ordem de número, data e alfabética)

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [29]:
df_nba.min() #Diferente da serie que o método 'min()' retorna o valor mínimo da serie, no DataFrame este método retorna valor mínimo de cada coluna (em ordem de número, data e alfabética)

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [30]:
df_nba.nlargest(n=4, columns='Salary') #Este método 'nlargest()' encontra os maiores valores. Precisa como parâmetros a quantidades de valores desejados para encontrar e em que coluna procurar. Neste caso procuramos os 4 jogadores com os maiores salários

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [31]:
df_nba.nsmallest(n=3, columns=['Birthday']) #Este método 'nsmallest()' encontra os menores valores. Precisa como parâmetros a quantidades de valores desejados para encontrar e em que coluna procurar. Neste caso procuramos os 3 jogadores mais velhos

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

Note que os métodos 'nlargest()' e 'nsmallest()' podem somente ser utilizados com colunas que possuem dados numéricos e datetime

df_nba.sum() -> 'DatetimeArray' with dtype datetime64[ns] does not support reduction 'sum'

In [32]:
df_nba.sum(numeric_only=True) #usando o método 'sum()' no DataFrame para descobir a soma de todos os salários, como visto na célula passada, retorna um erro. Por isso é utilizado o parâmetro numeri_only = True para ter a soma da coluna que possui somente números como tipo de dados

Salary    3444112694
dtype: int64

In [33]:
df_nba.mean(numeric_only=True) #Média salarial de todos os jogadores

Salary    7.653584e+06
dtype: float64

In [34]:
df_nba.median(numeric_only=True) #Mediana dos salários de todos os jogadores

Salary    3303074.5
dtype: float64

In [35]:
df_nba.mode(numeric_only=True) #Modo

   Salary
0   79568

In [36]:
df_nba.std(numeric_only=True) #Desvio padrão dos salários

Salary    9.288810e+06
dtype: float64

In [37]:
df_nba.sort_values(by = 'Name') #O método 'sort_values()' precisa de um parêmtro (nome da coluna) para pode ordenar

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [38]:
df_nba.sort_values(by = 'Name', ascending=False) #Por padrão o parâmetro 'ascending' vem como True e a ordem é crescente, para inverter é só colocar False no ascending

                  Name                   Team Position   Birthday    Salary
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
..                 ...                    ...      ...        ...       ...
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636

[450 rows x 5 columns]

In [39]:
df_nba.sort_values(by='Birthday', ascending=False).head() #Outra maneira de encontrar os jogadores mais novos sem utilizar o método 'nsamllest()'

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

In [40]:
df_nba.sort_values(by=['Team', 'Name']) #O método 'sort_values()' pode utilizar mais de uma coluna como parâmetro para ordenar o DataFrame seguindo a ordem da lista de colunas. Por padrão o ascending vai estar em True (ordem crescente). Neste exemplo primeiro vai seguir a ordem alfabética da coluna Team e depois a ordem alfabética da coluna Name

                Name                Team Position   Birthday    Salary
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
..               ...                 ...      ...        ...       ...
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000

[450 rows x 5 columns]

In [41]:
df_nba.sort_values(by = ['Team', 'Salary'],ascending=[True, False]) #O Team terá a ordem alfabética na ordem crescente e o Salary na ordem decrescente

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [42]:
df_nba = df_nba.sort_values(by = ['Team', 'Salary'],ascending=[True, False])

In [43]:
df_nba.head() #Como foi salvo na célula passada a ordem dos dados o DataFrame ficou com os índices fora da ordem

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

In [44]:
df_nba.sort_index().head() #Ordenou o DataFrame pelo índice. Por padrão o ascending está True e fica em ordem crescente

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [45]:
df_nba = df_nba.sort_index()
df_nba.head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [46]:
df_nba.sort_index(axis=1).head() #Ordenou os rótulos das colunas (axis=1) na ordem alfabética crescende. Por padrão o ascending vem True, caso queira colocar em ordem decrescente é só colocar o argumento ascending = False

    Birthday            Name Position   Salary                Team
0 1996-09-26    Shake Milton       SG  1445697  Philadelphia 76ers
1 1995-09-27  Christian Wood       PF  1645357     Detroit Pistons
2 1998-08-23   PJ Washington       PF  3831840   Charlotte Hornets
3 1988-10-04    Derrick Rose       PG  7317074     Detroit Pistons
4 1995-07-26   Marial Shayok        G    79568  Philadelphia 76ers

In [47]:
df_nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

df_nba = df_nba.set_index(keys='Name') #O método 'set_index()' transforma uma coluna para ser o índice do DataFrame

In [48]:
df_nba = pd.read_csv('nba.csv', parse_dates=['Birthday'], index_col='Name') #Quando formos criar um DataFrame podemos adicionar os parâmetros 'parse_dates' para mudar o tipo da coluna Birthday de string para datetime e o 'index_col' para colocar o índice como sendo a coluna Name

/tmp/ipykernel_28547/4098883685.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_nba = pd.read_csv('nba.csv', parse_dates=['Birthday'], index_col='Name') #Quando formos criar um DataFrame podemos adicionar os parâmetros 'parse_dates' para mudar o tipo da coluna Birthday de string para datetime e o 'index_col' para colocar o índice como sendo a coluna Name

In [49]:
df_nba.head()

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose       Detroit Pistons       PG 1988-10-04  7317074
Marial Shayok   Philadelphia 76ers        G 1995-07-26    79568

In [50]:
df_nba['Salary'] #Seleciona a coluna Salary somente (pode ser também df_nba.Salary, mas este código não dá pra selecionar mais de uma coluna)

Name
Shake Milton       1445697
Christian Wood     1645357
PJ Washington      3831840
Derrick Rose       7317074
Marial Shayok        79568
                    ...
Austin Rivers      2174310
Harry Giles        2578800
Robin Lopez        4767000
Collin Sexton      4764960
Ricky Rubio       16200000
Name: Salary, Length: 450, dtype: int64

In [51]:
df_nba[['Salary', 'Birthday']] #Lembrar que tem que ser uma lista para colocar como parâmetro, por isso [[]]

                  Salary   Birthday
Name
Shake Milton     1445697 1996-09-26
Christian Wood   1645357 1995-09-27
PJ Washington    3831840 1998-08-23
Derrick Rose     7317074 1988-10-04
Marial Shayok      79568 1995-07-26
...                  ...        ...
Austin Rivers    2174310 1992-08-01
Harry Giles      2578800 1998-04-22
Robin Lopez      4767000 1988-04-01
Collin Sexton    4764960 1999-01-04
Ricky Rubio     16200000 1990-10-21

[450 rows x 2 columns]

In [52]:
df_nba.select_dtypes(include='object') #Seleciona as colunas que possuem o dtype object

                               Team Position
Name
Shake Milton     Philadelphia 76ers       SG
Christian Wood      Detroit Pistons       PF
PJ Washington     Charlotte Hornets       PF
Derrick Rose        Detroit Pistons       PG
Marial Shayok    Philadelphia 76ers        G
...                             ...      ...
Austin Rivers       Houston Rockets       PG
Harry Giles        Sacramento Kings       PF
Robin Lopez         Milwaukee Bucks        C
Collin Sexton   Cleveland Cavaliers       PG
Ricky Rubio            Phoenix Suns       PG

[450 rows x 2 columns]

In [53]:
df_nba.select_dtypes(exclude=['object', 'int']) #Seleciona as colunas que não possuem o dtype object e int

                 Birthday
Name
Shake Milton   1996-09-26
Christian Wood 1995-09-27
PJ Washington  1998-08-23
Derrick Rose   1988-10-04
Marial Shayok  1995-07-26
...                   ...
Austin Rivers  1992-08-01
Harry Giles    1998-04-22
Robin Lopez    1988-04-01
Collin Sexton  1999-01-04
Ricky Rubio    1990-10-21

[450 rows x 1 columns]

In [54]:
df_nba.loc['LeBron James'] #Seleciona a linha cujo o índice é o nome do jogador retornando uma serie dos dados da linha

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [55]:
df_nba.loc[['Kawhi Leonard', 'Paul George']] #No DataFrame o método 'loc' permite selecionar multiplas linhas e retorna um DataFrame organizado as linhas pela ordem da lista. o método 'loc' aceita um parâmetro podendo ser um dado ou uma lista de dados, por isso do [[]]

                               Team Position   Birthday    Salary
Name
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556

In [56]:
df_nba.sort_index().loc['Otto Porter':'Patrick Beverley']#Utilizamos o 'sort_index' para organizar por índice (nomes dos jogadores) na ordem alfabética crescente e utilizamos o 'loc' para acessar os jogadores que estão entre o Otto Portter, menor valor, e o Patrick Beverley, maior valor -> ('Otto Porter':'Patrick Beverley'). Note que no slice do Pandas os dois valore são incluídos, diferente do Python que é [incluso:excluso]

                                  Team Position   Birthday    Salary
Name
Otto Porter              Chicago Bulls       SF 1993-06-03  27250576
PJ Dozier               Denver Nuggets       PG 1996-10-25     79568
PJ Washington        Charlotte Hornets       PF 1998-08-23   3831840
Pascal Siakam          Toronto Raptors       PF 1994-04-02   2351838
Pat Connaughton        Milwaukee Bucks       SG 1993-01-06   1723050
Patrick Beverley  Los Angeles Clippers       PG 1988-07-12  12345680

In [57]:
df_nba.sort_index().loc['Zach Collins':] #Faz um slice do Zach até o final

                                   Team Position   Birthday    Salary
Name
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham     New Orleans Pelicans       SF 1995-11-17     79568

In [58]:
df_nba.sort_index().loc[:'Al Horford'] #Faz um slice do Al Horford até o começo

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000

In [59]:
df_nba.iloc[300] #Acessa a linha pela posição do índice (iloc -> index location). Após os colchetes passe um número inetiro do índice que deseja obter a linha

Team             Denver Nuggets
Position                     PF
Birthday    1999-04-03 00:00:00
Salary                  1416852
Name: Jarred Vanderbilt, dtype: object

In [60]:
df_nba.iloc[[100, 200, 300, 400]] #O método 'iloc[]' pode acessar uma lista de posições de índices

                                Team Position   Birthday   Salary
Name
Brian Bowen           Indiana Pacers       SG 1998-10-02    79568
Marco Belinelli    San Antonio Spurs       SF 1986-03-25  5846154
Jarred Vanderbilt     Denver Nuggets       PF 1999-04-03  1416852
Louis King           Detroit Pistons        F 1999-04-06    79568

In [61]:
df_nba.iloc[400:404] #Podemos realizar o slicing no método iloc, contudo esse slice é igual ao do Python [includente:excludente]

                                    Team Position   Birthday    Salary
Name
Louis King               Detroit Pistons        F 1999-04-06     79568
Kostas Antetokounmpo  Los Angeles Lakers       PF 1997-11-20     79568
Rodions Kurucs             Brooklyn Nets       PF 1998-02-05   1699236
Spencer Dinwiddie          Brooklyn Nets       PG 1993-04-06  10605600

In [62]:
df_nba.iloc[:2] #Acessa do começo do índice até o índice 2 (excluindo o índice 2)

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [63]:
df_nba.iloc[447:] #Acessa do índice 447 até o final dos índices

                              Team Position   Birthday    Salary
Name
Robin Lopez        Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio           Phoenix Suns       PG 1990-10-21  16200000

In [64]:
df_nba.iloc[-10:-6] #Podemos passar valores negativos para acessar os índices finais

                                    Team Position   Birthday   Salary
Name
Jared Dudley          Los Angeles Lakers       PF 1985-07-10  2564753
Max Strus                  Chicago Bulls       SG 1996-03-28    79568
Kevon Looney       Golden State Warriors        C 1996-02-06  4464286
Willy Hernangomez      Charlotte Hornets        C 1994-05-27  1557250

In [65]:
df_nba.iloc[0:10:2] #Como no slice do Python, acessamos uma lista de índices do índice 1 até o 9 (o 10 é exclusivo) de 2 em 2

                             Team Position   Birthday    Salary
Name
Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
PJ Washington   Charlotte Hornets       PF 1998-08-23   3831840
Marial Shayok  Philadelphia 76ers        G 1995-07-26     79568
Kendrick Nunn          Miami Heat       SG 1995-08-03   1416852
Brook Lopez       Milwaukee Bucks        C 1988-04-01  12093024

Tanto o atributo loc como o iloc aceitam um segundo argumento representando a coluna(s) para acessar. Se usarmos o loc teremos que fornecer o nome da coluna, já o iloc temos que fornecer o número do índice

In [66]:
df_nba.loc['Giannis Antetokounmpo', 'Team']

'Milwaukee Bucks'

In [67]:
df_nba.loc['James Harden', ['Position', 'Birthday']] #Podemos fornecer uma lista com os nomes das colunas como argumento para o loc

Position                     PG
Birthday    1989-08-26 00:00:00
Name: James Harden, dtype: object

In [68]:
df_nba.loc[['Russell Westbrook', 'Anthony Davis'], ['Team', 'Birthday']] #Podemos fornecer uma lista como argumento tanto para o índice das linhas desejadas como para as colunas desejadas

                                 Team   Birthday
Name
Russell Westbrook     Houston Rockets 1988-11-12
Anthony Davis      Los Angeles Lakers 1993-03-11

In [69]:
df_nba.loc['Joel Embiid', 'Position':'Salary'] #Podemos utilizar o slicing para extrair multiplas colunas sem explicitar escrevendo seus nomes.

Position                      C
Birthday    1994-03-16 00:00:00
Salary                 27504630
Name: Joel Embiid, dtype: object

In [70]:
df_nba.loc['Joel Embiid', 'Salary':'Position'] # Devemos passar os nomes das colunas na ordem à qual eles aparecem no DataFrame. O pandas é incapaz de identificar qual coluna para colocar

Series([], Name: Joel Embiid, dtype: object)

In [71]:
df_nba.iloc[57, 3] #No método iloc foi passado o índice da linha (57) e da coluna (3 -> Salary)

np.int64(796806)

In [72]:
df_nba.iloc[100:104, :3] #Foi usado o slice na lista de índices da linha do DataFrame do índice 100 até 0 104 (lembre-se que aqui o slice é [inclusivo:exclusivo]). O mesmo vale para a lista dos índices das colunas (foi até o índice 3, mas excluindo esta que é o Salary)

                             Team Position   Birthday
Name
Brian Bowen        Indiana Pacers       SG 1998-10-02
Aaron Holiday      Indiana Pacers       PG 1996-09-30
Troy Daniels   Los Angeles Lakers       SG 1991-07-15
Buddy Hield      Sacramento Kings       SG 1992-12-17

O loc e iloc podem aceitar um único valor, lista de valores, um slicing de lista e muito mais. podemos utilizar atributos alternativos como o 'at' e o 'iat' quando queremos extrair somente um úncio valor do DataFrame

In [73]:
df_nba.at['Austin Rivers', 'Birthday'] #O atributo at aceita os rótulos da linha e coluna

Timestamp('1992-08-01 00:00:00')

In [74]:
df_nba.iat[263, 1] #O atributo iat aceita os índices da linha e coluna

'PF'

In [75]:
df_nba['Salary'].loc['Damian Lillard']

np.int64(29802321)

In [76]:
df_nba['Salary'].at['Damian Lillard']

np.int64(29802321)

In [77]:
df_nba['Salary'].iloc[234]

np.int64(2033160)

In [78]:
df_nba['Salary'].iat[234]

np.int64(2033160)

In [79]:
df_nba.columns

Index(['Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [80]:
df_nba.columns = ['Team', 'Position', 'Date of Birth', 'Pay'] #Foi renomeado os rótulos das colunas
df_nba.head(2)

                              Team Position Date of Birth      Pay
Name
Shake Milton    Philadelphia 76ers       SG    1996-09-26  1445697
Christian Wood     Detroit Pistons       PF    1995-09-27  1645357

In [81]:
df_nba.rename(columns={'Date of Birth': 'Birthday'}, inplace=True) #No método 'rename' é passado como parâmetro um dicionário, onde a chave é o nome a ser mudado da coluna e o valor é o novo nome da coluna. df.rename(columns={'nome_antigo': 'nome_novo'}. Para acontecer a troca é necessário o 'inplace=True'
df_nba.head(3)

                              Team Position   Birthday      Pay
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840

In [82]:
df_nba.rename(index={'Giannis Antetokounmpo': 'Geek Freak'}, inplace=True) #Muda o rótulo do índice da linha. É passado como parâmetro um dicionário, onde a chave é o nome a ser mudado da linha e o valor é o novo nome da linha

In [83]:
df_nba.loc['Geek Freak']

Team            Milwaukee Bucks
Position                     PF
Birthday    1994-12-06 00:00:00
Pay                    25842697
Name: Geek Freak, dtype: object

In [84]:
df_nba.set_index('Team').head() #Mudamos o índice de Name para Team, contudo a coluna Name não aparece mais

                   Position   Birthday      Pay
Team
Philadelphia 76ers       SG 1996-09-26  1445697
Detroit Pistons          PF 1995-09-27  1645357
Charlotte Hornets        PF 1998-08-23  3831840
Detroit Pistons          PG 1988-10-04  7317074
Philadelphia 76ers        G 1995-07-26    79568

In [123]:
df_nba.reset_index().set_index('Team').head() #Resetamos os índices do DataFrame e depois trocamos os índices das linhas para Team

                              Name Position   Birthday      Pay
Team
Philadelphia 76ers    Shake Milton       SG 1996-09-26  1445697
Detroit Pistons     Christian Wood       PF 1995-09-27  1645357
Charlotte Hornets    PJ Washington       PF 1998-08-23  3831840
Detroit Pistons       Derrick Rose       PG 1988-10-04  7317074
Philadelphia 76ers   Marial Shayok        G 1995-07-26    79568

In [132]:
df_nba.reset_index()
df_nba.set_index('Team')

                    Position   Birthday       Pay
Team
Philadelphia 76ers        SG 1996-09-26   1445697
Detroit Pistons           PF 1995-09-27   1645357
Charlotte Hornets         PF 1998-08-23   3831840
Detroit Pistons           PG 1988-10-04   7317074
Philadelphia 76ers         G 1995-07-26     79568
...                      ...        ...       ...
Houston Rockets           PG 1992-08-01   2174310
Sacramento Kings          PF 1998-04-22   2578800
Milwaukee Bucks            C 1988-04-01   4767000
Cleveland Cavaliers       PG 1999-01-04   4764960
Phoenix Suns              PG 1990-10-21  16200000

[450 rows x 3 columns]

In [133]:
df_nba.set_index('Team').loc['Detroit Pistons']

                Position   Birthday       Pay
Team
Detroit Pistons       PF 1995-09-27   1645357
Detroit Pistons       PG 1988-10-04   7317074
Detroit Pistons       PG 1991-12-09   7333333
Detroit Pistons       SF 1997-06-10   1416852
Detroit Pistons       SG 1996-08-15   1416852
Detroit Pistons       SF 2000-12-23   3285120
Detroit Pistons       PG 1990-04-16  18086956
Detroit Pistons       PG 1990-11-01   1620564
Detroit Pistons        C 1997-02-25   3569643
Detroit Pistons       SG 1996-06-24   3827160
Detroit Pistons        C 1993-08-10  27093018
Detroit Pistons       PF 1989-09-02   3200000
Detroit Pistons       SG 1996-05-08   1416852
Detroit Pistons       SF 1991-11-10  11392857
Detroit Pistons       PF 1989-03-16  34449964
Detroit Pistons        F 1999-04-06     79568

###Exercícios

In [86]:
df_nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'])
df_nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [87]:
df_nfl.set_index('Name') #df_nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'], index_col = 'Name')

                                    Team Position   Birthday   Salary
Name
Tremon Smith         Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams        Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler         New England Patriots       DT 1994-04-12   645000
Derek Wolfe               Denver Broncos       DE 1990-02-24  8000000
Jake Ryan           Jacksonville Jaguars      OLB 1992-02-27  1000000
...                                  ...      ...        ...      ...
Bashaud Breeland      Kansas City Chiefs       CB 1992-01-30   805000
Craig James          Philadelphia Eagles       CB 1996-04-29   570000
Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
Chuma Edoga                New York Jets       OT 1997-05-25   495000
Tajae Sharpe            Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 4 columns]

In [88]:
df_nfl['Team'].value_counts().head()

Team
New York Jets          58
Kansas City Chiefs     56
Washington Redskins    56
New Orleans Saints     55
San Francisco 49Ers    55
Name: count, dtype: int64

In [ ]:
df_nfl.nlargest(n=5, columns='Salary') #Ou poderia fazer df_nlf.sort_values('Salary', ascending=False).head()

                 Name                  Team Position   Birthday    Salary
180      Kirk Cousins     Minnesota Vikings       QB 1988-08-19  27500000
905    Marcus Mariota      Tennessee Titans       QB 1993-10-30  20922000
1623   Jameis Winston  Tampa Bay Buccaneers       QB 1994-01-06  20922000
1343       Derek Carr       Oakland Raiders       QB 1991-03-28  19900000
150   Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [90]:
df_nfl.sort_values('Salary', ascending=False).head()

                 Name                  Team Position   Birthday    Salary
180      Kirk Cousins     Minnesota Vikings       QB 1988-08-19  27500000
1623   Jameis Winston  Tampa Bay Buccaneers       QB 1994-01-06  20922000
905    Marcus Mariota      Tennessee Titans       QB 1993-10-30  20922000
1343       Derek Carr       Oakland Raiders       QB 1991-03-28  19900000
150   Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [94]:
df_nfl.sort_values(by = ['Team', 'Salary'], ascending=[True, False])

                    Name                 Team Position   Birthday    Salary
1577      Chandler Jones    Arizona Cardinals      OLB 1990-02-27  16500000
669     Patrick Peterson    Arizona Cardinals       CB 1990-07-11  11000000
1361    Larry Fitzgerald    Arizona Cardinals       WR 1983-08-31  11000000
1594       David Johnson    Arizona Cardinals       RB 1991-12-16   5700000
948          Justin Pugh    Arizona Cardinals        G 1990-08-15   5000000
...                  ...                  ...      ...        ...       ...
1109  Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
1325       Kelvin Harmon  Washington Redskins       WR 1996-12-15    495000
1344          Wes Martin  Washington Redskins        G 1996-05-09    495000
1345      Jimmy Moreland  Washington Redskins       CB 1995-08-26    495000
1509       Jeremy Reaves  Washington Redskins       SS 1996-08-29    495000

[1655 rows x 5 columns]

In [149]:
df_nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'])
df_nfl = df_nfl.set_index(keys='Team').loc['New York Jets'].nsmallest(1, 'Birthday')
df_nfl

                     Name Position   Birthday   Salary
Team
New York Jets  Ryan Kalil        C 1985-03-29  2400000

Summary

- The DataFrame is a two-dimensional data structure consisting of rows and columns.
- The DataFrame shares attributes and methods with the Series. Many of the attributes and methods operate differently due to the dimensional differences between the two objects.
- The 'sort_values' method sorts one or more DataFrame columns. We can assign each column a different sort order (ascending or descending).
- The 'loc' attribute extracts rows or columns by index label. The at attribute is a convenient shortcut for targeting only one value.
- The 'iloc' attribute extracts rows or columns by index position. The iat attribute is a convenient shortcut for targeting only one value.
- The 'reset_index' method restores an index as a regular column in the DataFrame.
- The 'rename method' sets a different name for one or more columns or rows.