In [1]:
import pandas as pd
import numpy as np

###Reshaping and pivoting

Um conjunto de dados pode chegar em um formato inadequado para a análise que gostaríamos de realizar.
Às vezes, os problemas se restringem a uma coluna, linha ou célula específica. Uma coluna pode ter o tipo de dados errado, uma linha pode ter valores ausentes ou uma célula pode ter maiúsculas e minúsculas incorretas. 

Em outras ocasiões, um conjunto de dados pode ter problemas estruturais maiores que se estendem além dos dados. Talvez o conjunto de dados armazene seus valores em um formato que facilita a extração de uma única linha, mas dificulta a agregação dos dados.

Remodelar um conjunto de dados significa manipulá-lo em um formato diferente, um que conte uma história que não poderia ser obtida a partir de sua apresentação original. A remodelação oferece uma nova visão ou perspectiva sobre os dados. Essa habilidade é fundamental; um estudo estima que 80% da análise de dados consiste em limpar os dados e moldá-los no formato adequado.

###Dados amplos vs. estreitos

Antes de explorarmos mais métodos, vamos falar brevemente sobre a estrutura de um conjunto de dados. 

Um conjunto de dados pode armazenar seus valores em formato amplo ou estreito. 

Um conjunto de dados estreito também é chamado de conjunto de dados longo ou alto. Esses nomes refletem a direção em que o conjunto de dados se expande à medida que adicionamos mais valores a ele. 

Um conjunto de dados amplo aumenta em largura; ele cresce para os lados. Um conjunto de dados estreito/longo/alto aumenta em altura; ele cresce para baixo.

Um conjunto de dados amplo se expande horizontalmente. A expansão horizontal é algo ruim? Não necessariamente. Um conjunto de dados amplo é ideal para visualizar o panorama geral — a história completa. Mas o formato amplo também tem suas desvantagens.
O conjunto de dados torna-se mais difícil de trabalhar à medida que adicionamos mais colunas.

Um conjunto de dados estreito cresce verticalmente. Um formato estreito facilita a manipulação de dados existentes e a adição de novos registros. Cada variável é isolada em uma única coluna.

O formato de armazenamento ideal para um conjunto de dados depende da informação que estamos tentando obter dele. O Pandas oferece ferramentas para transformar DataFrames de formatos estreitos para formatos amplos e vice-versa.

In [3]:
df = pd.read_csv('sales_by_employee.csv')
df.head()

     Date   Name       Customer  Revenue  Expenses
0  1/1/20  Oscar  Logistics XYZ     5250       531
1  1/1/20  Oscar    Money Corp.     4406       661
2  1/2/20  Oscar     PaperMaven     8661      1401
3  1/3/20  Oscar    PaperGenius     7075       906
4  1/4/20  Oscar    Paper Pound     2524      1767

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      26 non-null     object
 1   Name      26 non-null     object
 2   Customer  26 non-null     object
 3   Revenue   26 non-null     int64
 4   Expenses  26 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

In [12]:
df = pd.read_csv('sales_by_employee.csv', parse_dates = ['Date'])
df.head()

/tmp/ipykernel_23083/924782882.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('sales_by_employee.csv', parse_dates = ['Date'])

        Date   Name       Customer  Revenue  Expenses
0 2020-01-01  Oscar  Logistics XYZ     5250       531
1 2020-01-01  Oscar    Money Corp.     4406       661
2 2020-01-02  Oscar     PaperMaven     8661      1401
3 2020-01-03  Oscar    PaperGenius     7075       906
4 2020-01-04  Oscar    Paper Pound     2524      1767

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      26 non-null     datetime64[ns]
 1   Name      26 non-null     object
 2   Customer  26 non-null     object
 3   Revenue   26 non-null     int64
 4   Expenses  26 non-null     int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 1.1+ KB

###O método pivot_table


Uma tabela dinâmica agrega os valores de uma coluna e agrupa os resultados usando os valores de outras colunas.
A palavra agregar descreve um cálculo de resumo que envolve múltiplos valores.
Exemplos de agregações incluem média, soma, mediana e contagem.

In [16]:
df.pivot_table(index = 'Date', aggfunc= 'sum')

,Customer,Expenses,Name,Revenue
Date,,,,
2020-01-01,Logistics XYZMoney Corp.Logistics XYZPaperGeni...,3825,OscarOscarMichaelJimDwightCreed,25761
2020-01-02,PaperMavenPaperGeniusMoney Corp.Average Paper ...,6222,OscarMichaelJimCreedCreed,36515
2020-01-03,PaperGeniusPaperGeniusPaper PoundLogistics XYZ...,7882,OscarMichaelJimDwightDwightDwight,29195
2020-01-04,Paper PoundBest Paper Co.PaperMavenAverage Pap...,7253,OscarMichaelJimJimCreed,19740
2020-01-05,Paper PoundBest Paper Co.Paper PoundMoney Corp.,4785,OscarMichaelDwightCreed,19339

In [17]:
df.pivot_table(index = 'Date', values = 'Revenue', aggfunc= 'sum')

            Revenue
Date
2020-01-01    25761
2020-01-02    36515
2020-01-03    29195
2020-01-04    19740
2020-01-05    19339

Para agregar valores em várias colunas, podemos passar uma lista de colunas como argumento.
Temos a soma da receita agrupada por data.