In [97]:
import pandas as pd
import numpy as np

In [98]:
df_inspections = pd.read_csv('chicago_food_inspections.csv')
df_inspections.head()

                          Name             Risk
0   MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                  JETS PIZZA   Risk 2 (Medium)
2                   ROOM 1520      Risk 3 (Low)
3    MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                CHARTWELLS       Risk 1 (High)

In [99]:
df_inspections['Name'].head()

0     MARRIOT MARQUIS CHICAGO
1                    JETS PIZZA
2                     ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                  CHARTWELLS
Name: Name, dtype: object

In [100]:
df_inspections['Name'].head().values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

In [101]:
df_inspections['Name'].str.strip().head() #O método strip() retira os espaços antes e depois do texto, como no Python

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [102]:
df_inspections['Name'] = df_inspections['Name'].str.strip()

In [103]:
df_inspections

                                Name             Risk
0            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
1                         JETS PIZZA  Risk 2 (Medium)
2                          ROOM 1520     Risk 3 (Low)
3            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
4                         CHARTWELLS    Risk 1 (High)
...                              ...              ...
153805                     WOLCOTT'S    Risk 1 (High)
153806  DUNKIN DONUTS/BASKIN-ROBBINS  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   mr.daniel's    Risk 1 (High)
153809                    TEMPO CAFE    Risk 1 (High)

[153810 rows x 2 columns]

In [104]:
df_inspections['Name'].str.lower().head() #O método lower() transforma todo o texto em minúsculo, como no Python

0    marriot marquis chicago
1                 jets pizza
2                  room 1520
3    marriot marquis chicago
4                 chartwells
Name: Name, dtype: object

In [105]:
df_inspections['Name'].str.upper().head() #O método upper() transforma todo o texto em maiúscula, como no Python

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [106]:
df_inspections['Name'].str.capitalize().head() #O método capitalize() transforma toda 1° letra do texto em maiúscula, como no Python

0    Marriot marquis chicago
1                 Jets pizza
2                  Room 1520
3    Marriot marquis chicago
4                 Chartwells
Name: Name, dtype: object

In [107]:
df_inspections['Name'].str.title().head() #O método title() transforma todo o começo do texto em maiúscula, como no Python

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

In [108]:
df_inspections['Name'] = df_inspections['Name'].str.title()
df_inspections.head()

                      Name             Risk
0  Marriot Marquis Chicago    Risk 1 (High)
1               Jets Pizza  Risk 2 (Medium)
2                Room 1520     Risk 3 (Low)
3  Marriot Marquis Chicago    Risk 1 (High)
4               Chartwells    Risk 1 (High)

In [109]:
df_inspections['Risk'].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [110]:
df_inspections['Risk'].unique() #Mostra quais os valores únicos do DataFrame, note que existem valores NaN e all

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [111]:
df_inspections = df_inspections.dropna(subset=['Risk']) #Foram retirados os valores NaN da coluna Risk

In [112]:
df_inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All'],
      dtype=object)

In [113]:
df_inspections = df_inspections.replace(to_replace='All', value='Risk 4 (Extreme)') #Transformou o valor 'All' em 'Risk 4 (Extreme)'

In [114]:
df_inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [115]:
df_inspections['Risk'].str.slice(5,6).head() #Mostra do índíce 5 no texto até o 6 [5:6] -> [inclusivo:exclusivo]

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [116]:
df_inspections['Risk'].str[8:-1].head() #outra forma de usar o slice mostrando do índice 8 no texto até o último índice

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [117]:
df_inspections['Name'].str.lower().str.contains('pizza').head() #Transforma todo o texto em minúsculo e confere se contêm a palavra pizza

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [118]:
has_pizza = df_inspections['Name'].str.lower().str.contains('pizza')
df_inspections[has_pizza].head()

                             Name             Risk
1                      Jets Pizza  Risk 2 (Medium)
19  Nancy'S Home Of Stuffed Pizza    Risk 1 (High)
27     Nary'S Grill & Pizza ,Inc.    Risk 1 (High)
29            Narys Grill & Pizza    Risk 1 (High)
68                  Colutas Pizza    Risk 1 (High)

In [119]:
df_inspections['Name'].str.lower().str.startswith('tacos').head()

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [120]:
start_with_tacos = df_inspections['Name'].str.lower().str.startswith('tacos') #Transforma todo o texto para minúsculo, depois procura pelos textos que começam com a palavra tacos
df_inspections[start_with_tacos]

                         Name           Risk
69               Tacos Nietos  Risk 1 (High)
556       Tacos El Tio 2 Inc.  Risk 1 (High)
675          Tacos Don Gabino  Risk 1 (High)
958       Tacos El Tio 2 Inc.  Risk 1 (High)
1036      Tacos El Tio 2 Inc.  Risk 1 (High)
...                       ...            ...
143587          Tacos De Luna  Risk 1 (High)
144026           Tacos Garcia  Risk 1 (High)
146174        Tacos Place'S 1  Risk 1 (High)
147810  Tacos Mario'S Limited  Risk 1 (High)
151191            Tacos Reyna  Risk 1 (High)

[105 rows x 2 columns]

In [121]:
end_with_tacos = df_inspections['Name'].str.lower().str.endswith('tacos') #Transforma todo o texto para minúsculo, depois procura pelos textos que terminam com a palavra tacos
df_inspections[end_with_tacos]

                   Name           Risk
382        Lazo'S Tacos  Risk 1 (High)
569        Lazo'S Tacos  Risk 1 (High)
2652       Flying Tacos   Risk 3 (Low)
3250       Jony'S Tacos  Risk 1 (High)
3812       Paco'S Tacos  Risk 1 (High)
...                 ...            ...
151121      Reyes Tacos  Risk 1 (High)
151318   El Macho Tacos  Risk 1 (High)
151801   El Macho Tacos  Risk 1 (High)
153087  Raymond'S Tacos  Risk 1 (High)
153504        Mis Tacos  Risk 1 (High)

[304 rows x 2 columns]

In [122]:
df_custumers = pd.read_csv('customers.csv')
df_custumers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [123]:
df_custumers['Name'].str.len().head() #O método str.len() retorna o número de caracteres dos valores da coluna Name

0    13
1    17
2    15
3    19
4    14
Name: Name, dtype: int64

In [124]:
df_custumers['Name'].str.split(' ').head() #O método str.split() irá separar o texto pelos espaços (' ') e colocará as palavras em uma lista

0           [Frank, Manning]
1       [Elizabeth, Johnson]
2         [Donald, Stephens]
3    [Michael, Vincent, III]
4          [Jasmine, Zamora]
Name: Name, dtype: object

In [125]:
df_custumers['Name'].str.split(' ').str.len().head() #O método str.split() irá separar o texto pelos espaços (' ') e colocará as palavras em uma lista e o método str.len() mostra o tamanho dos componentes da lista

0    2
1    2
2    2
3    3
4    2
Name: Name, dtype: int64

In [126]:
df_custumers['Name'].str.split(pat = ' ', n=1).head() #O método str.split() irá separar o texto pelos espaços (' ') e colocará as palavras em uma lista e o n=1 o número máximo de splits

0          [Frank, Manning]
1      [Elizabeth, Johnson]
2        [Donald, Stephens]
3    [Michael, Vincent III]
4         [Jasmine, Zamora]
Name: Name, dtype: object

In [127]:
df_custumers['Name'].str.split(pat=' ', n=1).str.get(0).head() #O método str.split() irá separar o texto pelos espaços (' ') e colocará as palavras em uma lista e o n=1 o número máximo de splits e o método str.get(0) seleciona o primeiro elemento (índice 0)

0        Frank
1    Elizabeth
2       Donald
3      Michael
4      Jasmine
Name: Name, dtype: object

In [128]:
df_custumers['Name'].str.split(pat=' ', n=1).str.get(1).head() #O método str.split() irá separar o texto pelos espaços (' ') e colocará as palavras em uma lista e o n=1 o número máximo de splits e o método str.get(1) seleciona o segundo elemento (índice 1). O método str.get() suporta números negativos (de trás para frente em relacão aos índices)

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [129]:
df_custumers['Name'].str.split(pat=' ', n=1, expand= True).head() #O parâmetro expand = True cria um dataframe com duas colunas com os índices 0 e 1. Caso não coloque o parâmetro n=1 o Pandas vai expandir para todas as palavras e as que não tiverem ele coloca None no lugar

           0            1
0      Frank      Manning
1  Elizabeth      Johnson
2     Donald     Stephens
3    Michael  Vincent III
4    Jasmine       Zamora

In [130]:
df_custumers[['First Name', 'Last Name']] = df_custumers['Name'].str.split(pat=' ', n=1, expand=True) #Foram cradas duas colunas no DataFrame df_custumes e colocado os valores das colunas expendidas

In [131]:
df_custumers

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [132]:
df_custumers = df_custumers.drop(labels='Name', axis='columns') #Foi excluído a coluna Name de DataFrame
df_custumers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora

In [133]:
df_custumers['Address'].head()

0    6461 Quinn Groves, East Matthew, New Hampshire...
1    1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2    19120 Fleming Manors, Prestonstad, Montana, 23495
3         441 Olivia Creek, Jimmymouth, Georgia, 82991
4    4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
Name: Address, dtype: object

In [134]:
df_custumers['Address'].str.split(pat= ', ', n=3, expand=True).head()

                            0             1              2      3
0           6461 Quinn Groves  East Matthew  New Hampshire  16656
1  1360 Tracey Ports Apt. 419      Kyleport        Vermont  31924
2        19120 Fleming Manors   Prestonstad        Montana  23495
3            441 Olivia Creek    Jimmymouth        Georgia  82991
4  4246 Chelsey Ford Apt. 310     Karamouth           Utah  76252

In [135]:
df_custumers[['Street', 'City', 'State', 'Zip']] = df_custumers['Address'].str.split(pat=', ', n=3, expand=True)
df_custumers

,Address,First Name,Last Name,Street,City,State,Zip
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581

In [136]:
df_custumers = df_custumers.drop(labels='Address', axis='columns')
df_custumers

,First Name,Last Name,Street,City,State,Zip
0,Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana,Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda,Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric,Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor,Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry,Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581

Summary
-> The str attribute holds a StringMethods object with methods for performing string manipulations on Series values.
-> The strip family of methods removes whitespace from the start of a string, the end of a string, or both sides.
-> Methods such as upper, lower, capitalize, and title modify the letter casing of string characters.
-> The contains method checks for the presence of a substring within another string.
-> The startswith method checks for a substring at the beginning of a string.
-> The complementary endswith method checks for a substring at the end of a string.
-> The split method splits a string into a list by using a specified delimiter. We can use it to split a DataFrame column’s text across several Series.