In [2]:
import pandas as pd
import numpy as np

In [3]:
df_employees = pd.read_csv('./employees.csv', parse_dates=['Start Date'])
df_employees

/tmp/ipykernel_16362/1913654741.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_employees = pd.read_csv('./employees.csv', parse_dates=['Start Date'])

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [4]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [5]:
df_employees['Mgmt'].astype(bool) #Transformou a coluna Mgmt de tipo object para bool

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [6]:
df_employees['Mgmt'] = df_employees['Mgmt'].astype(bool) #Transformando o tipo de dado da coluna Mgmt para booleano

In [7]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [8]:
df_employees['Salary'].fillna(0).tail() #Transformou os falores NaN da coluna Salary para 0

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         0.0
Name: Salary, dtype: float64

In [9]:
df_employees['Salary'].fillna(0).astype(int).tail()

996      42392
997      96914
998      60500
999     129949
1000         0
Name: Salary, dtype: int64

In [10]:
df_employees['Salary'] = df_employees['Salary'].fillna(0).astype(int)

In [11]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int64(1), object(3)
memory usage: 40.2+ KB

In [12]:
df_employees.nunique() #Mostr quantos valores únicos o DataFrame possui

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [13]:
df_employees['Gender'].astype('category') #Transforma o tipo de dado desta coluna para category

0         Male
1         Male
2       Female
3          NaN
4         Male
         ...
996       Male
997       Male
998       Male
999       Male
1000       NaN
Name: Gender, Length: 1001, dtype: category
Categories (2, object): ['Female', 'Male']

In [14]:
df_employees['Gender'] = df_employees['Gender'].astype('category') #salva a transformação

In [15]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [16]:
df_employees['Team'].astype('category') #Transforma o tipo de dado desta coluna para category

0          Marketing
1                NaN
2            Finance
3            Finance
4                 IT
            ...
996          Finance
997          Product
998     Business Dev
999            Sales
1000             NaN
Name: Team, Length: 1001, dtype: category
Categories (10, object): ['Business Dev', 'Distribution', 'Engineering', 'Finance', ..., 'Legal', 'Marketing', 'Product', 'Sales']

In [17]:
df_employees['Team'] = df_employees['Team'].astype('category') #salva a transformação

In [18]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

In [19]:
df_employees['First Name'] == 'Maria' #Verifica em toda a serie se existe a palavra Maria, caso exista retorna True se não False. Chamado serie booleana percorrendo toda a coluna e classificando True ou False para a operação que foi pedida (== 'Maria')

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [20]:
df_employees[df_employees['First Name'] == 'Maria'] #utilizando a serie booleana retorna as linhas que deram True

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [21]:
marias = df_employees['First Name'] == 'Maria' #Este código percorre a serie e os dados que possuem True para a comparação dataframe['coluna] == 'condição' e a linha é adiconada a variável marias
df_employees[marias]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [22]:
df_employees['Team'] != 'Finance'

0        True
1        True
2       False
3       False
4        True
        ...
996     False
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [23]:
df_employees[df_employees['Team'] != 'Finance'] #utilizando a serie booleana retorna as linhas que deram False

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [24]:
high_earners = df_employees['Salary'] > 100000
high_earners.head()

0    False
1    False
2     True
3     True
4     True
Name: Salary, dtype: bool

In [25]:
df_employees[df_employees['Salary'] > 100000].head()

  First Name  Gender Start Date  Salary   Mgmt          Team
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
9    Frances  Female 2002-08-08  139852   True  Business Dev

In [26]:
is_female = df_employees['Gender'] == 'Female'
is_female

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Gender, Length: 1001, dtype: bool

In [27]:
in_biz_dev = df_employees['Team'] == 'Business Dev'
in_biz_dev

0       False
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998      True
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [28]:
df_employees[is_female & in_biz_dev].head() #Interceção das duas series utlizando o operador lógico and (&)

   First Name  Gender Start Date  Salary   Mgmt          Team
9     Frances  Female 2002-08-08  139852   True  Business Dev
33       Jean  Female 1993-12-18  119082  False  Business Dev
36     Rachel  Female 2009-02-16  142032  False  Business Dev
38  Stephanie  Female 1986-09-13   36844   True  Business Dev
61     Denise  Female 2001-11-06  106862  False  Business Dev

In [29]:
is_manager = df_employees['Mgmt']
df_employees[is_female & in_biz_dev & is_manager].head() #Podemos utilizar duas ou mais series utilizando o and

    First Name  Gender Start Date  Salary  Mgmt          Team
9      Frances  Female 2002-08-08  139852  True  Business Dev
38   Stephanie  Female 1986-09-13   36844  True  Business Dev
66       Nancy  Female 2012-12-15  125250  True  Business Dev
92       Linda  Female 2000-05-25  119009  True  Business Dev
111     Bonnie  Female 1999-12-17   42153  True  Business Dev

In [30]:
earning_below_40k = df_employees['Salary'] < 40000
earning_below_40k

0        True
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Salary, Length: 1001, dtype: bool

In [31]:
started_after_2015 = df_employees['Start Date'] > '2015-01-01'
started_after_2015

0       False
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Start Date, Length: 1001, dtype: bool

In [32]:
df_employees[earning_below_40k|started_after_2015].head() #Interceção das duas series utlizando o operador lógico or (|), o pandas coloca também as linhas que possuem True e True também

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
7         NaN  Female 2015-07-20   45906   True    Finance
15    Lillian  Female 2016-06-05   59414  False    Product
25        NaN    Male 2012-10-08   37076   True         IT
26      Craig    Male 2000-02-27   37598   True  Marketing

In [33]:
df_employees[~ (df_employees['Salary'] < 40000)].head() #Interceção da serie utlizando o operador lógico not (~), aqui vou invertido para as linhas que recebem mais de 40000

  First Name  Gender Start Date  Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933   True      NaN
2      Maria  Female        NaT  130590  False  Finance
3      Jerry     NaN 2005-03-04  138705   True  Finance
4      Larry    Male 1998-01-24  101004   True       IT
5     Dennis    Male 1987-04-18  115163  False    Legal

In [34]:
sales = df_employees['Team'] == 'Sales'
legal = df_employees['Team'] == 'Legal'
mktg = df_employees['Team'] == 'Marketing'
df_employees[sales | legal | mktg].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [35]:
all_star_teams = ['Sales','Legal','Marketing']  #Utilizado quando se deseja fazer muitas comparações com o or
on_all_star_teams = df_employees['Team'].isin(all_star_teams)
df_employees[on_all_star_teams].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [36]:
between_80K_and_90K = df_employees['Salary'].between(80000, 90000) #Foi usado o método 'between' na coluna Salary para mostras as pessoas que ganham de 80.000 até 90.000. Este resultado é (includente:excludente)
df_employees[between_80K_and_90K].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [37]:
eighties_folk = df_employees['Start Date'].between(left='1980-01-01', right='1990-01-01') #between pode ser usado para datas também
df_employees[eighties_folk].head()

   First Name  Gender Start Date  Salary   Mgmt     Team
5      Dennis    Male 1987-04-18  115163  False    Legal
6        Ruby  Female 1987-08-17   65476   True  Product
10     Louise  Female 1980-08-12   63241   True      NaN
12    Brandon    Male 1980-12-01  112807   True       HR
17      Shawn    Male 1986-12-07  111737  False  Product

In [38]:
name_starts_with_r = df_employees['First Name'].between('R', 'S') #between pode ser usado para strings também
df_employees[name_starts_with_r].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
6        Ruby  Female 1987-08-17   65476   True       Product
36     Rachel  Female 2009-02-16  142032  False  Business Dev
45      Roger    Male 1980-04-17   88010   True         Sales
67     Rachel  Female 1999-08-16   51178   True       Finance
78      Robin  Female 1983-06-04  114797   True         Sales

In [ ]:
df_employees['Team'].isnull().head() #O método isnull() retorna o serie booler na coluna Team quais as linhas que possuem o NaN como True

0    False
1     True
2    False
3    False
4    False
Name: Team, dtype: bool

In [ ]:
df_employees['Start Date'].isnull().head() #O método isnull() retorna o serie booler na coluna Team quais as linhas que possuem o NaN como True

0    False
1    False
2     True
3    False
4    False
Name: Start Date, dtype: bool

In [ ]:
df_employees['Team'].notnull().head() #O método notnull() retorna o serie booler na coluna Team quais as linhas que não possuem o NaN como True

0     True
1    False
2     True
3     True
4     True
Name: Team, dtype: bool

In [ ]:
no_team = df_employees['Team'].isnull() #inclue em uma variável as linhas com os valores NaN na coluna Team
df_employees[no_team].head() #Retorna as linhas dos valores armazenados na variável no_team

   First Name  Gender Start Date  Salary   Mgmt Team
1      Thomas    Male 1996-03-31   61933   True  NaN
10     Louise  Female 1980-08-12   63241   True  NaN
23        NaN    Male 2012-06-14  125792   True  NaN
32        NaN    Male 1998-08-21  122340   True  NaN
91      James     NaN 2005-01-26  128771  False  NaN

In [ ]:
has_name = df_employees['First Name'].notnull() #inclue em uma variável as linhas com os valores que não possuem NaN na coluna First Name
df_employees[has_name].head()#Retorna as linhas dos valores armazenados na variável no_team

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT

Os métodos 'isnull' e 'notnull' são os melhores métodos para filtrar de forma rápida a presença de valores perdidos ou não presentes em uma ou mais linhas

In [45]:
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'])
employees

/tmp/ipykernel_16362/2285922707.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv('employees.csv', parse_dates=['Start Date'])

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [ ]:
employees.dropna() #o método dropna() deletou todas as linhas que possuiam valores NaNs do dataframe

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[761 rows x 6 columns]

In [ ]:
employees.dropna(how='all').tail() #o parâmetro how recebe o argumento 'all' para remover todas as linhas que possuem todos os valores NaN. Por padrão o parâmetro how possue o argumento 'any' que remove as linhas que possue pelo menos um valor NaN

    First Name Gender Start Date    Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483.0  False  Distribution
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [ ]:
employees.dropna(how='any').tail() #Note que na célula passada a linha de índice 995 possui um valor NaN na coluna Gender e irá sumir com o parâmetro how = 'any'

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [ ]:
employees.dropna(subset=['Gender']).tail() #Podemos usar o parâmetro 'subset' para linhas com valores NaN em colunas específicas

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [ ]:
employees.dropna(subset=['Start Date', 'Salary']).head() #Podemos passar para o parâmetro subset uma lista com colunas para restirar as linhas que possuem valores NaN

  First Name  Gender Start Date    Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933.0   True      NaN
3      Jerry     NaN 2005-03-04  138705.0   True  Finance
4      Larry    Male 1998-01-24  101004.0   True       IT
5     Dennis    Male 1987-04-18  115163.0  False    Legal
6       Ruby  Female 1987-08-17   65476.0   True  Product

In [54]:
employees['Team'].head()

0    Marketing
1          NaN
2      Finance
3      Finance
4           IT
Name: Team, dtype: object

In [ ]:
employees['Team'].duplicated().head() #mesma coisa employees['Team].duplicate(keep = 'first').head()

#O método duplicated retorna uma serie booleana que identifica duplicatas nas colunas. O método marca a primeira ocorrência como não duplicado (False), todos os outros valores duplicados depois serão marcados como True

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [ ]:
employees['Team'].duplicated(keep='last') #Marcar as últimas ocorrências de valores duplicadas

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [ ]:
(~employees['Team'].duplicated()).head() #inverte

0     True
1     True
2     True
3    False
4     True
Name: Team, dtype: bool

In [58]:
first_one_in_team = ~employees['Team'].duplicated()
employees[first_one_in_team]

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [59]:
employees.drop_duplicates()

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [ ]:
employees.drop_duplicates(subset=['Team']) #Retorna quais índices apareceu pela primeira vez os valores únicos da coluna Team

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

O método drop_duplicates também aceita o parâmetro keep

In [ ]:
employees.drop_duplicates(subset=['Team'], keep='last') #Retorna quais índices apareceu pela última vez os valores únicos da coluna Team

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638.0  False            HR
989      Justin     NaN 1991-02-10   38344.0  False         Legal
990       Robin  Female 1987-07-24  100765.0   True            IT
993        Tina  Female 1997-05-15   56450.0   True   Engineering
994      George    Male 2013-06-21   98874.0   True     Marketing
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

In [ ]:
employees.drop_duplicates(subset=['First Name'], keep=False) #Retorna quais nomes apareceram pela primeira vez os valores únicos da coluna First Name. O argumento False irá excluir todas as linhas com valores duplicados

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male 1987-04-18  115163.0  False         Legal
8       Angela  Female 2005-11-22   95570.0   True   Engineering
33        Jean  Female 1993-12-18  119082.0  False  Business Dev
190      Carol  Female 1996-03-19   57783.0  False       Finance
291      Tammy  Female 1984-11-11  132839.0   True            IT
495     Eugene    Male 1984-05-24   81077.0  False         Sales
688      Brian    Male 2007-04-07   93901.0   True         Legal
832      Keith    Male 2003-02-12  120672.0  False         Legal
887      David    Male 2009-12-05   92242.0  False         Legal

In [ ]:
name_is_doulgas = employees['First Name'] == 'Douglas' #usando a serie bolleana para armazenar na variável as linhas que possuem a palavra Doulgas na coluna First Name
is_male = employees['Gender'] == 'Male'  #usando a serie bolleana para armazenar na variável as linhas que possuem a palavra Male na coluna Gender
employees[name_is_doulgas & is_male] #Retorna as linhas que possuem Doulgas na coluna First Name e Male na coluna Gender

    First Name Gender Start Date    Salary   Mgmt         Team
0      Douglas   Male 1993-08-06       NaN   True    Marketing
217    Douglas   Male 1999-09-03   83341.0   True           IT
322    Douglas   Male 2002-01-08   41428.0  False      Product
835    Douglas   Male 2007-08-04  132175.0  False  Engineering

In [ ]:
employees.drop_duplicates(subset=['Gender', 'Team']).head() #Retorna todos os valores que possuem duplicação na coluna Gender e First Name. Caso uma das duplicadas seja falso, retornará, por exemplo: First Name Douglas e Gender Male, irá aparecer se o Fisrt Name Douglas e Gender NaN (que é diferente de Male)

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

###Exercício

In [88]:
df_netflix = pd.read_csv('netflix.csv')
df_netflix

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

In [89]:
df_netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'])

/tmp/ipykernel_16362/1538501218.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'])

In [77]:
df_netflix

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [90]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [91]:
df_netflix['type'].astype('category')

0       TV Show
1         Movie
2       TV Show
3         Movie
4         Movie
         ...
5832      Movie
5833      Movie
5834      Movie
5835      Movie
5836    TV Show
Name: type, Length: 5837, dtype: category
Categories (2, object): ['Movie', 'TV Show']

In [92]:
df_netflix['type'] = df_netflix['type'].astype('category')

In [93]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [94]:
df_netflix

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [ ]:
df_netflix['title'] == 'Limitless'

0       False
1       False
2       False
3       False
4       False
        ...
5832    False
5833    False
5834    False
5835    False
5836    False
Name: title, Length: 5837, dtype: bool

In [95]:
name_title = df_netflix['title'] == 'Limitless' 
df_netflix[name_title]

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [ ]:
df_netflix[df_netflix['title'] == 'Limitless'] #resposta do livro

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [96]:
diretor = df_netflix['director'] == 'Robert Rodriguez'
filme = df_netflix['type'] == 'Movie'
df_netflix[diretor & filme]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [97]:
data = df_netflix['date_added'] == '2019-07-31'
diretor_2 = df_netflix['director'] == 'Robert Altman'
df_netflix[data | diretor_2]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

In [98]:
all_directors = ['Orson Welles', 'Aditya Kripalani', 'Sam Raimi']
on_all_directors = df_netflix['director'].isin(all_directors)
df_netflix[on_all_directors]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [99]:
all_date = df_netflix['date_added'].between(left='2019-05-01', right='2019-06-01')
df_netflix[all_date]

,title,director,date_added,type
29,Chopsticks,Sachin Yardi,2019-05-31,Movie
60,Away From Home,NaN,2019-05-08,TV Show
82,III Smoking Barrels,Sanjib Dey,2019-06-01,Movie
108,Jailbirds,NaN,2019-05-10,TV Show
124,Pegasus,Han Han,2019-05-31,Movie
...,...,...,...,...
5671,Satan & Adam,V. Scott Balcerek,2019-06-01,Movie
5675,Rim of the World,McG,2019-05-24,Movie
5677,Malibu Rescue,Savage Steve Holland,2019-05-13,Movie
5739,Mission Istaanbul: Darr Ke Aagey Jeet Hai,Apoorva Lakhia,2019-05-16,Movie
5829,The Kindness Diaries,NaN,2019-05-01,TV Show

In [100]:
df_netflix.dropna(subset=['director'])

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

In [ ]:
df_netflix.drop_duplicates(subset=['date_added'], keep=False) #Resposta do livro

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie

In [ ]:
first_date = df_netflix['date_added'].duplicated()
df_netflix[first_date]
#Errada

,title,director,date_added,type
18,The Rugrats Movie,Igor Kovalyov,2019-10-01,Movie
21,A Dangerous Woman,Stephen Gyllenhaal,2018-04-01,Movie
35,Inconceivable,Jonathan Baker,2018-03-01,Movie
39,Terrace House: Aloha State,NaN,NaT,TV Show
42,Tiffany Haddish Presents: They Ready,NaN,2019-08-13,TV Show
...,...,...,...,...
5832,The Pursuit,John Papola,2019-08-07,Movie
5833,Hurricane Bianca,Matt Kugelman,2017-01-01,Movie
5834,Amar's Hands,Khaled Youssef,2019-04-26,Movie
5835,Bill Nye: Science Guy,Jason Sussberg,2018-04-25,Movie
5836,Age of Glory,NaN,NaT,TV Show