In [2]:
import pandas as pd
import numpy as np

In [4]:
df_inspections = pd.read_csv('chicago_food_inspections.csv')
df_inspections.head()

                          Name             Risk
0   MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                  JETS PIZZA   Risk 2 (Medium)
2                   ROOM 1520      Risk 3 (Low)
3    MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                CHARTWELLS       Risk 1 (High)

In [5]:
df_inspections['Name'].head()

0     MARRIOT MARQUIS CHICAGO
1                    JETS PIZZA
2                     ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                  CHARTWELLS
Name: Name, dtype: object

In [7]:
df_inspections['Name'].head().values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

In [ ]:
df_inspections['Name'].str.strip().head() #O método strip() retira os espaços antes e depois do texto, como no Python

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [10]:
df_inspections['Name'] = df_inspections['Name'].str.strip()

In [11]:
df_inspections

                                Name             Risk
0            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
1                         JETS PIZZA  Risk 2 (Medium)
2                          ROOM 1520     Risk 3 (Low)
3            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
4                         CHARTWELLS    Risk 1 (High)
...                              ...              ...
153805                     WOLCOTT'S    Risk 1 (High)
153806  DUNKIN DONUTS/BASKIN-ROBBINS  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   mr.daniel's    Risk 1 (High)
153809                    TEMPO CAFE    Risk 1 (High)

[153810 rows x 2 columns]

In [ ]:
df_inspections['Name'].str.lower().head() #O método lower() transforma todo o texto em minúsculo, como no Python

0    marriot marquis chicago
1                 jets pizza
2                  room 1520
3    marriot marquis chicago
4                 chartwells
Name: Name, dtype: object

In [ ]:
df_inspections['Name'].str.upper().head() #O método upper() transforma todo o texto em maiúscula, como no Python

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [ ]:
df_inspections['Name'].str.capitalize().head() #O método capitalize() transforma toda 1° letra do texto em maiúscula, como no Python

0    Marriot marquis chicago
1                 Jets pizza
2                  Room 1520
3    Marriot marquis chicago
4                 Chartwells
Name: Name, dtype: object

In [ ]:
df_inspections['Name'].str.title().head() #O método title() transforma todo o começo do texto em maiúscula, como no Python

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

In [18]:
df_inspections['Name'] = df_inspections['Name'].str.title()
df_inspections.head()

                      Name             Risk
0  Marriot Marquis Chicago    Risk 1 (High)
1               Jets Pizza  Risk 2 (Medium)
2                Room 1520     Risk 3 (Low)
3  Marriot Marquis Chicago    Risk 1 (High)
4               Chartwells    Risk 1 (High)

In [19]:
df_inspections['Risk'].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [ ]:
df_inspections['Risk'].unique() #Mostra quais os valores únicos do DataFrame, note que existem valores NaN e all

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [ ]:
df_inspections = df_inspections.dropna(subset=['Risk']) #Foram retirados os valores NaN da coluna Risk

In [22]:
df_inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All'],
      dtype=object)

In [ ]:
df_inspections = df_inspections.replace(to_replace='All', value='Risk 4 (Extreme)') #Transformou o valor 'All' em 'Risk 4 (Extreme)'

In [24]:
df_inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [ ]:
df_inspections['Risk'].str.slice(5,6).head() #Mostra do índíce 5 no texto até o 6 [5:6] -> [inclusivo:exclusivo]

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [ ]:
df_inspections['Risk'].str[8:-1].head() #outra forma de usar o slice mostrando do índice 8 no texto até o último índice

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [ ]:
#df_inspections['Name'].str.lower().contains('pizza').head()