In [1]:
import pandas as pd
import numpy as np

In [2]:
address = ("8809 Flair Square", "Toddside", "IL", "37206")
address

('8809 Flair Square', 'Toddside', 'IL', '37206')

In [3]:
addresses = [
("8809 Flair Square", "Toddside", "IL", "37206"),
("9901 Austin Street", "Toddside", "IL", "37206"),
("905 Hogan Quarter", "Franklin", "IL", "37206"),
]

In [ ]:
pd.MultiIndex.from_tuples(addresses) #Forma um MultiIndex onde o primeiro valor das tuplas é o endereço, o segundo valor é a cidade, o terceiro valor é o estado e o quarto valor é o código zip

MultiIndex([( '8809 Flair Square', 'Toddside', 'IL', '37206'),
            ('9901 Austin Street', 'Toddside', 'IL', '37206'),
            ( '905 Hogan Quarter', 'Franklin', 'IL', '37206')],
           )

In [5]:
row_index = pd.MultiIndex.from_tuples(
    tuples = addresses,
    names = ['Street', 'City', 'State', 'Zip']
)
row_index

MultiIndex([( '8809 Flair Square', 'Toddside', 'IL', '37206'),
            ('9901 Austin Street', 'Toddside', 'IL', '37206'),
            ( '905 Hogan Quarter', 'Franklin', 'IL', '37206')],
           names=['Street', 'City', 'State', 'Zip'])

In [6]:
data = [
["A", "B+"],
["C+", "C"],
["D-", "A"],
]
columns = ["Schools", "Cost of Living"]

In [7]:
area_grades = pd.DataFrame(data=data, index=row_index, columns=columns)
area_grades

                                        Schools Cost of Living
Street             City     State Zip
8809 Flair Square  Toddside IL    37206       A             B+
9901 Austin Street Toddside IL    37206      C+              C
905 Hogan Quarter  Franklin IL    37206      D-              A

In [8]:
area_grades.columns

Index(['Schools', 'Cost of Living'], dtype='object')

In [10]:
column_index = pd.MultiIndex.from_tuples([
    ('Culture', 'Restaurants'),
    ('Culture', 'Museums'),
    ('Services', 'Police'),
    ('Services', 'Schools')
])
column_index

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           )

In [11]:
data = [
["C-", "B+", "B-", "A"],
["D+", "C", "A", "C+"],
["A-", "A", "D+", "F"]
]

In [12]:
pd.DataFrame(data=data, index=row_index, columns=column_index)

                                            Culture         Services
                                        Restaurants Museums   Police Schools
Street             City     State Zip
8809 Flair Square  Toddside IL    37206          C-      B+       B-       A
9901 Austin Street Toddside IL    37206          D+       C        A      C+
905 Hogan Quarter  Franklin IL    37206          A-       A       D+       F

In [13]:
df_neighbor = pd.read_csv('neighborhoods.csv')
df_neighbor

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Culture,Culture.1,Services,Services.1
0,NaN,NaN,NaN,Restaurants,Museums,Police,Schools
1,State,City,Street,NaN,NaN,NaN,NaN
2,MO,Fisherborough,244 Tracy View,C+,F,D-,A+
3,SD,Port Curtisville,446 Cynthia Inlet,C-,B,B,D+
4,WV,Jimenezview,432 John Common,A,A+,F,B
...,...,...,...,...,...,...,...
248,MI,North Matthew,055 Clayton Isle,B-,C,B,C+
249,MT,Chadton,601 Richards Road,A-,D,D+,D
250,SC,Diazmouth,385 Robin Harbors,F,D,B-,D+
251,VA,Laurentown,255 Gonzalez Land,C+,B-,F,D-
252,NE,South Kennethmouth,346 Wallace Pass,C-,B-,A,A-

In [15]:
df_neighbor = pd.read_csv('neighborhoods.csv', index_col=[0,1,2], header=[0,1])
df_neighbor.head()

                                             Culture         Services
                                         Restaurants Museums   Police Schools
State City             Street
MO    Fisherborough    244 Tracy View             C+       F       D-      A+
SD    Port Curtisville 446 Cynthia Inlet          C-       B        B      D+
WV    Jimenezview      432 John Common             A      A+        F       B
AK    Stevenshire      238 Andrew Rue             D-       A       A-      A-
ND    New Joshuaport   877 Walter Neck            D+      C-        B       B

In [16]:
df_neighbor.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 251 entries, ('MO', 'Fisherborough', '244 Tracy View') to ('NE', 'South Kennethmouth', '346 Wallace Pass')
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Culture, Restaurants)  251 non-null    object
 1   (Culture, Museums)      251 non-null    object
 2   (Services, Police)      251 non-null    object
 3   (Services, Schools)     251 non-null    object
dtypes: object(4)
memory usage: 27.1+ KB

In [17]:
df_neighbor.index

MultiIndex([('MO',      'Fisherborough',        '244 Tracy View'),
            ('SD',   'Port Curtisville',     '446 Cynthia Inlet'),
            ('WV',        'Jimenezview',       '432 John Common'),
            ('AK',        'Stevenshire',        '238 Andrew Rue'),
            ('ND',     'New Joshuaport',       '877 Walter Neck'),
            ('ID',         'Wellsville',   '696 Weber Stravenue'),
            ('TN',          'Jodiburgh',    '285 Justin Corners'),
            ('DC',   'Lake Christopher',   '607 Montoya Harbors'),
            ('OH',          'Port Mike',      '041 Michael Neck'),
            ('ND',         'Hardyburgh', '550 Gilmore Mountains'),
            ...
            ('AK',          'Scottstad',      '114 Jones Garden'),
            ('IA',    'Port Willieport',  '320 Jennifer Mission'),
            ('ME',         'Port Linda',        '692 Hill Glens'),
            ('KS',         'Kaylamouth',       '483 Freeman Via'),
            ('WA',     'Port Shawnfort',    '691 Winters Bridge'),
            ('MI',      'North Matthew',      '055 Clayton Isle'),
            ('MT',            'Chadton',     '601 Richards Road'),
            ('SC',          'Diazmouth',     '385 Robin Harbors'),
            ('VA',         'Laurentown',     '255 Gonzalez Land'),
            ('NE', 'South Kennethmouth',      '346 Wallace Pass')],
           names=['State', 'City', 'Street'], length=251)

In [18]:
df_neighbor.columns

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           )

In [19]:
df_neighbor.index.names

FrozenList(['State', 'City', 'Street'])

In [21]:
df_neighbor.index.get_level_values('City')

Index(['Fisherborough', 'Port Curtisville', 'Jimenezview', 'Stevenshire',
       'New Joshuaport', 'Wellsville', 'Jodiburgh', 'Lake Christopher',
       'Port Mike', 'Hardyburgh',
       ...
       'Scottstad', 'Port Willieport', 'Port Linda', 'Kaylamouth',
       'Port Shawnfort', 'North Matthew', 'Chadton', 'Diazmouth', 'Laurentown',
       'South Kennethmouth'],
      dtype='object', name='City', length=251)

In [22]:
df_neighbor.columns.names

FrozenList([None, None])

In [23]:
df_neighbor.columns.names = ['Category', 'Subcategory']
df_neighbor.columns.names

FrozenList(['Category', 'Subcategory'])

In [24]:
df_neighbor.head(3)

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
State City             Street
MO    Fisherborough    244 Tracy View             C+       F       D-      A+
SD    Port Curtisville 446 Cynthia Inlet          C-       B        B      D+
WV    Jimenezview      432 John Common             A      A+        F       B

In [25]:
df_neighbor.columns.get_level_values('Category')

Index(['Culture', 'Culture', 'Services', 'Services'], dtype='object', name='Category')

In [26]:
df_neighbor.nunique()

Category  Subcategory
Culture   Restaurants    13
          Museums        13
Services  Police         13
          Schools        13
dtype: int64

In [27]:
df_neighbor.sort_index()

Category                                      Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Stevenshire    238 Andrew Rue                D-       A       A-      A-
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Martintown     013 Bell Mills                C-       D       A-      B-
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire     717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [29]:
df_neighbor.sort_index(ascending=False).head(4)

Category                                   Culture         Services
Subcategory                            Restaurants Museums   Police Schools
State City        Street
WY    Reneeshire  717 Patel Square               B      B+        D       A
      Port Jason  624 Faulkner Orchard          A-       F       C+      C+
      Martintown  013 Bell Mills                C-       D       A-      B-
      Lake Nicole 933 Jennifer Burg              C      A+       A-       C

In [30]:
df_neighbor.sort_index(ascending=[True, False, True]).head()

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
State City           Street
AK    Stevenshire    238 Andrew Rue               D-       A       A-      A-
      Scottstad      082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D
      Rowlandchester 386 Rebecca Cove             C-      A-       A+       C
AL    Vegaside       191 Mindy Meadows            B+      A-       A+      D+

In [ ]:
df_neighbor.sort_index(level='City') #Irá colocar em ordem crescente a coluna City

Category                                      Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City          Street
AR    Allisonland   124 Diaz Brooks                C-      A+        F      C+
GA    Amyburgh      941 Brian Expressway            B       B       D-      C+
IA    Amyburgh      163 Heather Neck                F       D       A+      A-
ID    Andrewshire   952 Ellis Drive                C+      A-       C+       A
UT    Baileyfort    919 Stewart Hills              D+      C+        A       C
...                                               ...     ...      ...     ...
NC    West Scott    348 Jack Branch                A-      D-       A-       A
SD    West Scott    139 Hardy Vista                C+      A-       D+      B-
IN    Wilsonborough 066 Carr Road                  A+      C-        B       F
NC    Wilsonshire   871 Christopher Vista          B+       B       D+       F
NV    Wilsonshire   542 Jessica Stream              A      A+       C-      C+

[251 rows x 4 columns]

In [32]:
df_neighbor.sort_index(level=['City', 'Street']).head()

Category                                   Culture         Services
Subcategory                            Restaurants Museums   Police Schools
State City        Street
AR    Allisonland 124 Diaz Brooks               C-      A+        F      C+
IA    Amyburgh    163 Heather Neck               F       D       A+      A-
GA    Amyburgh    941 Brian Expressway           B       B       D-      C+
ID    Andrewshire 952 Ellis Drive               C+      A-       C+       A
VT    Baileyfort  831 Norma Cove                 B      D+       A+      D+

In [34]:
df_neighbor.sort_index(level=['City', 'Street'], ascending=[True, False]).head()

Category                                   Culture         Services
Subcategory                            Restaurants Museums   Police Schools
State City        Street
AR    Allisonland 124 Diaz Brooks               C-      A+        F      C+
GA    Amyburgh    941 Brian Expressway           B       B       D-      C+
IA    Amyburgh    163 Heather Neck               F       D       A+      A-
ID    Andrewshire 952 Ellis Drive               C+      A-       C+       A
UT    Baileyfort  919 Stewart Hills             D+      C+        A       C

In [35]:
df_neighbor.sort_index(axis=1).head(3)

Category                                 Culture             Services
Subcategory                              Museums Restaurants   Police Schools
State City             Street
MO    Fisherborough    244 Tracy View          F          C+       D-      A+
SD    Port Curtisville 446 Cynthia Inlet       B          C-        B      D+
WV    Jimenezview      432 John Common        A+           A        F       B

In [36]:
df_neighbor.sort_index(axis=1, level='Subcategory', ascending=False).head(3)

Category                                 Services     Culture Services Culture
Subcategory                               Schools Restaurants   Police Museums
State City             Street
MO    Fisherborough    244 Tracy View          A+          C+       D-       F
SD    Port Curtisville 446 Cynthia Inlet       D+          C-        B       B
WV    Jimenezview      432 John Common          B           A        F      A+

In [38]:
df_neighbor = df_neighbor.sort_index(ascending=True)
df_neighbor.head(3)

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove             C-      A-       A+       C
      Scottstad      082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D

In [39]:
df_neighbor['Services']

Subcategory                               Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A+       C
      Scottstad      082 Leblanc Freeway       D      B+
                     114 Jones Garden          D       D
      Stevenshire    238 Andrew Rue           A-      A-
AL    Clarkland      430 Douglas Mission      C+      B+
...                                          ...     ...
WY    Lake Nicole    754 Weaver Turnpike       B       D
                     933 Jennifer Burg        A-       C
      Martintown     013 Bell Mills           A-      B-
      Port Jason     624 Faulkner Orchard     C+      C+
      Reneeshire     717 Patel Square          D       A

[251 rows x 2 columns]

In [ ]:
df_neighbor['Services']['Schools'] #ou neighborhoods[("Services", "Schools")]

State  City            Street
AK     Rowlandchester  386 Rebecca Cove         C
       Scottstad       082 Leblanc Freeway     B+
                       114 Jones Garden         D
       Stevenshire     238 Andrew Rue          A-
AL     Clarkland       430 Douglas Mission     B+
                                               ..
WY     Lake Nicole     754 Weaver Turnpike      D
                       933 Jennifer Burg        C
       Martintown      013 Bell Mills          B-
       Port Jason      624 Faulkner Orchard    C+
       Reneeshire      717 Patel Square         A
Name: Schools, Length: 251, dtype: object

In [43]:
df_neighbor[[('Services', 'Schools'), ('Culture', 'Museums')]]

Category                                  Services Culture
Subcategory                                Schools Museums
State City           Street
AK    Rowlandchester 386 Rebecca Cove            C      A-
      Scottstad      082 Leblanc Freeway        B+      C-
                     114 Jones Garden            D      D-
      Stevenshire    238 Andrew Rue             A-       A
AL    Clarkland      430 Douglas Mission        B+       F
...                                            ...     ...
WY    Lake Nicole    754 Weaver Turnpike         D      D-
                     933 Jennifer Burg           C      A+
      Martintown     013 Bell Mills             B-       D
      Port Jason     624 Faulkner Orchard       C+       F
      Reneeshire     717 Patel Square            A      B+

[251 rows x 2 columns]

In [44]:
columns = [
    ('Services', 'Schools'),
    ('Culture', 'Museums')
]

df_neighbor[columns]

Category                                  Services Culture
Subcategory                                Schools Museums
State City           Street
AK    Rowlandchester 386 Rebecca Cove            C      A-
      Scottstad      082 Leblanc Freeway        B+      C-
                     114 Jones Garden            D      D-
      Stevenshire    238 Andrew Rue             A-       A
AL    Clarkland      430 Douglas Mission        B+       F
...                                            ...     ...
WY    Lake Nicole    754 Weaver Turnpike         D      D-
                     933 Jennifer Burg           C      A+
      Martintown     013 Bell Mills             B-       D
      Port Jason     624 Faulkner Orchard       C+       F
      Reneeshire     717 Patel Square            A      B+

[251 rows x 2 columns]

In [45]:
df_neighbor.loc[('TX', 'Kingchester', '534 Gordon Falls')]

Category  Subcategory
Culture   Restaurants     C
          Museums        D+
Services  Police          B
          Schools         B
Name: (TX, Kingchester, 534 Gordon Falls), dtype: object

In [46]:
df_neighbor.loc['CA']

Category                              Culture         Services
Subcategory                       Restaurants Museums   Police Schools
City           Street
Dustinmouth    793 Cynthia Square          A-      A+       C-       A
North Jennifer 303 Alisha Road             D-      C+       C+      A+
Ryanfort       934 David Run                F      B+        F      D-

In [47]:
df_neighbor.loc['CA', 'Dustinmouth']

Category               Culture         Services
Subcategory        Restaurants Museums   Police Schools
Street
793 Cynthia Square          A-      A+       C-       A

In [48]:
df_neighbor.loc['CA', 'Culture']

Subcategory                       Restaurants Museums
City           Street
Dustinmouth    793 Cynthia Square          A-      A+
North Jennifer 303 Alisha Road             D-      C+
Ryanfort       934 David Run                F      B+

In [49]:
df_neighbor.loc[('CA', 'Dustinmouth')]

Category               Culture         Services
Subcategory        Restaurants Museums   Police Schools
Street
793 Cynthia Square          A-      A+       C-       A

In [50]:
df_neighbor.loc[('CA', 'Dustinmouth'), ('Services')]

Subcategory        Police Schools
Street
793 Cynthia Square     C-       A

In [52]:
df_neighbor.loc[('CA', 'Dustinmouth'), ('Services', 'Schools')]

Street
793 Cynthia Square    A
Name: (Services, Schools), dtype: object

In [59]:
df_neighbor.loc["NE":"NH"]

Category                                          Culture         Services  \
Subcategory                                   Restaurants Museums   Police
State City               Street
NE    Barryborough       460 Anna Tunnel               A+      A+        B
      Shawnchester       802 Cook Cliff                D-      D+        D
      South Kennethmouth 346 Wallace Pass              C-      B-        A
      South Nathan       821 Jake Fork                 C+       D       D+
NH    Courtneyfort       697 Spencer Isle              A+      A+       C+
      East Deborahberg   271 Ryan Mount                 B       C       D+
      Ingramton          430 Calvin Underpass          C+      D+        C
      North Latoya       603 Clark Mount               D-      A-       B+
      South Tara         559 Michael Glens             C-      C-        F

Category
Subcategory                                   Schools
State City               Street
NE    Barryborough       460 Anna Tunnel            A
      Shawnchester       802 Cook Cliff             A
      South Kennethmouth 346 Wallace Pass          A-
      South Nathan       821 Jake Fork              A
NH    Courtneyfort       697 Spencer Isle          A+
      East Deborahberg   271 Ryan Mount            B-
      Ingramton          430 Calvin Underpass      C-
      North Latoya       603 Clark Mount           B-
      South Tara         559 Michael Glens          B

In [56]:
df_neighbor.loc[('NE', 'Shawnchester'):('NH', 'North Latoya')]

Category                                          Culture         Services  \
Subcategory                                   Restaurants Museums   Police
State City               Street
NE    Shawnchester       802 Cook Cliff                D-      D+        D
      South Kennethmouth 346 Wallace Pass              C-      B-        A
      South Nathan       821 Jake Fork                 C+       D       D+
NH    Courtneyfort       697 Spencer Isle              A+      A+       C+
      East Deborahberg   271 Ryan Mount                 B       C       D+
      Ingramton          430 Calvin Underpass          C+      D+        C
      North Latoya       603 Clark Mount               D-      A-       B+

Category
Subcategory                                   Schools
State City               Street
NE    Shawnchester       802 Cook Cliff             A
      South Kennethmouth 346 Wallace Pass          A-
      South Nathan       821 Jake Fork              A
NH    Courtneyfort       697 Spencer Isle          A+
      East Deborahberg   271 Ryan Mount            B-
      Ingramton          430 Calvin Underpass      C-
      North Latoya       603 Clark Mount           B-

In [57]:
start = ('NE', 'Shawnchester')
end = ('NH', 'North Latoya')
df_neighbor.loc[start:end]

Category                                          Culture         Services  \
Subcategory                                   Restaurants Museums   Police
State City               Street
NE    Shawnchester       802 Cook Cliff                D-      D+        D
      South Kennethmouth 346 Wallace Pass              C-      B-        A
      South Nathan       821 Jake Fork                 C+       D       D+
NH    Courtneyfort       697 Spencer Isle              A+      A+       C+
      East Deborahberg   271 Ryan Mount                 B       C       D+
      Ingramton          430 Calvin Underpass          C+      D+        C
      North Latoya       603 Clark Mount               D-      A-       B+

Category
Subcategory                                   Schools
State City               Street
NE    Shawnchester       802 Cook Cliff             A
      South Kennethmouth 346 Wallace Pass          A-
      South Nathan       821 Jake Fork              A
NH    Courtneyfort       697 Spencer Isle          A+
      East Deborahberg   271 Ryan Mount            B-
      Ingramton          430 Calvin Underpass      C-
      North Latoya       603 Clark Mount           B-

In [58]:
df_neighbor.loc[('NE', 'Shawnchester'):'NH']

Category                                          Culture         Services  \
Subcategory                                   Restaurants Museums   Police
State City               Street
NE    Shawnchester       802 Cook Cliff                D-      D+        D
      South Kennethmouth 346 Wallace Pass              C-      B-        A
      South Nathan       821 Jake Fork                 C+       D       D+
NH    Courtneyfort       697 Spencer Isle              A+      A+       C+
      East Deborahberg   271 Ryan Mount                 B       C       D+
      Ingramton          430 Calvin Underpass          C+      D+        C
      North Latoya       603 Clark Mount               D-      A-       B+
      South Tara         559 Michael Glens             C-      C-        F

Category
Subcategory                                   Schools
State City               Street
NE    Shawnchester       802 Cook Cliff             A
      South Kennethmouth 346 Wallace Pass          A-
      South Nathan       821 Jake Fork              A
NH    Courtneyfort       697 Spencer Isle          A+
      East Deborahberg   271 Ryan Mount            B-
      Ingramton          430 Calvin Underpass      C-
      North Latoya       603 Clark Mount           B-
      South Tara         559 Michael Glens          B

In [ ]:
df_neighbor.iloc[25] #Linha com o índice 25

Category  Subcategory
Culture   Restaurants    A+
          Museums         A
Services  Police         A+
          Schools        C+
Name: (CT, East Jessicaland, 208 Todd Knolls), dtype: object

In [ ]:
df_neighbor.iloc[25, 2] #Linha com o índice 25 e coluna com o índice 2 (Subcategory)

'A+'

In [ ]:
df_neighbor.iloc[[25, 30]] #linhas com os índices 25 e 30

Category                                   Culture         Services
Subcategory                            Restaurants Museums   Police Schools
State City             Street
CT    East Jessicaland 208 Todd Knolls          A+       A       A+      C+
DC    East Lisaview    910 Sandy Ramp           A-      A+        B       B

In [ ]:
df_neighbor.iloc[25:30] #as linhas dos índices 25 até o 30, mas ao contrário do .loc[inclusivo:inclusivo] o .iloc[inclusivo:exclusivo]

Category                                       Culture         Services  \
Subcategory                                Restaurants Museums   Police
State City             Street
CT    East Jessicaland 208 Todd Knolls              A+       A       A+
      New Adrianhaven  048 Brian Cove               A-      C+       A+
      Port Mike        410 Keith Lodge              D-       A       B+
      Sethstad         139 Bailey Grove              C      C-       C+
DC    East Jessica     149 Norman Crossing          A-      C-       C+

Category
Subcategory                                Schools
State City             Street
CT    East Jessicaland 208 Todd Knolls          C+
      New Adrianhaven  048 Brian Cove           D-
      Port Mike        410 Keith Lodge           D
      Sethstad         139 Bailey Grove         A+
DC    East Jessica     149 Norman Crossing      A-

In [ ]:
df_neighbor.iloc[25:30, 1:3] #as linhas dos índices 25 até o 30 e as colunas do índices 1 até o 3. O Pandas aceita valores negativos

Category                                   Culture Services
Subcategory                                Museums   Police
State City             Street
CT    East Jessicaland 208 Todd Knolls           A       A+
      New Adrianhaven  048 Brian Cove           C+       A+
      Port Mike        410 Keith Lodge           A       B+
      Sethstad         139 Bailey Grove         C-       C+
DC    East Jessica     149 Norman Crossing      C-       C+

In [65]:
df_neighbor.xs(key='Lake Nicole', level='City')

Category                      Culture         Services
Subcategory               Restaurants Museums   Police Schools
State Street
OR    650 Angela Track              D      C-        D       F
WY    754 Weaver Turnpike           B      D-        B       D
      933 Jennifer Burg             C      A+       A-       C

In [67]:
df_neighbor.xs(axis='columns', key='Museums', level='Subcategory').head()

Category                                 Culture
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A-
      Scottstad      082 Leblanc Freeway      C-
                     114 Jones Garden         D-
      Stevenshire    238 Andrew Rue            A
AL    Clarkland      430 Douglas Mission       F

In [68]:
df_neighbor.xs(key=('AK', '238 Andrew Rue'), level=[0,2])

Category        Culture         Services
Subcategory Restaurants Museums   Police Schools
City
Stevenshire          D-       A       A-      A-

In [69]:
new_order = ['City', 'State', 'Street']
df_neighbor.reorder_levels(order=new_order).head()

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove             C-      A-       A+       C
Scottstad      AK    082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D
Stevenshire    AK    238 Andrew Rue               D-       A       A-      A-
Clarkland      AL    430 Douglas Mission           A       F       C+      B+

In [70]:
df_neighbor.reorder_levels(order=[1,0,2]).head()

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove             C-      A-       A+       C
Scottstad      AK    082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D
Stevenshire    AK    238 Andrew Rue               D-       A       A-      A-
Clarkland      AL    430 Douglas Mission           A       F       C+      B+

In [72]:
df_neighbor.reset_index().tail()

Category    State         City                Street     Culture          \
Subcategory                                          Restaurants Museums
246            WY  Lake Nicole   754 Weaver Turnpike           B      D-
247            WY  Lake Nicole     933 Jennifer Burg           C      A+
248            WY   Martintown        013 Bell Mills          C-       D
249            WY   Port Jason  624 Faulkner Orchard          A-       F
250            WY   Reneeshire      717 Patel Square           B      B+

Category    Services
Subcategory   Police Schools
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

In [73]:
df_neighbor.reset_index(col_level='Subcategory').tail()

Category                                                 Culture          \
Subcategory State         City                Street Restaurants Museums
246            WY  Lake Nicole   754 Weaver Turnpike           B      D-
247            WY  Lake Nicole     933 Jennifer Burg           C      A+
248            WY   Martintown        013 Bell Mills          C-       D
249            WY   Port Jason  624 Faulkner Orchard          A-       F
250            WY   Reneeshire      717 Patel Square           B      B+

Category    Services
Subcategory   Police Schools
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

In [74]:
df_neighbor.reset_index(col_fill='Address', col_level='Subcategory').tail()

Category    Address                                        Culture          \
Subcategory   State         City                Street Restaurants Museums
246              WY  Lake Nicole   754 Weaver Turnpike           B      D-
247              WY  Lake Nicole     933 Jennifer Burg           C      A+
248              WY   Martintown        013 Bell Mills          C-       D
249              WY   Port Jason  624 Faulkner Orchard          A-       F
250              WY   Reneeshire      717 Patel Square           B      B+

Category    Services
Subcategory   Police Schools
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

In [75]:
df_neighbor.reset_index(level='Street').tail()

Category                         Street     Culture         Services
Subcategory                             Restaurants Museums   Police Schools
State City
WY    Lake Nicole   754 Weaver Turnpike           B      D-        B       D
      Lake Nicole     933 Jennifer Burg           C      A+       A-       C
      Martintown         013 Bell Mills          C-       D       A-      B-
      Port Jason   624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire       717 Patel Square           B      B+        D       A

In [76]:
df_neighbor.reset_index(level=['Street', 'City']).tail()

Category            City                Street     Culture         Services  \
Subcategory                                    Restaurants Museums   Police
State
WY           Lake Nicole   754 Weaver Turnpike           B      D-        B
WY           Lake Nicole     933 Jennifer Burg           C      A+       A-
WY            Martintown        013 Bell Mills          C-       D       A-
WY            Port Jason  624 Faulkner Orchard          A-       F       C+
WY            Reneeshire      717 Patel Square           B      B+        D

Category
Subcategory Schools
State
WY                D
WY                C
WY               B-
WY               C+
WY                A

In [77]:
df_neighbor.reset_index(level='Street', drop = True).tail()

Category              Culture         Services
Subcategory       Restaurants Museums   Police Schools
State City
WY    Lake Nicole           B      D-        B       D
      Lake Nicole           C      A+       A-       C
      Martintown           C-       D       A-      B-
      Port Jason           A-       F       C+      C+
      Reneeshire            B      B+        D       A

In [78]:
df_neighbor = df_neighbor.reset_index()

In [80]:
df_neighbor

Category    State            City                Street     Culture          \
Subcategory                                             Restaurants Museums
0              AK  Rowlandchester      386 Rebecca Cove          C-      A-
1              AK       Scottstad   082 Leblanc Freeway           D      C-
2              AK       Scottstad      114 Jones Garden          D-      D-
3              AK     Stevenshire        238 Andrew Rue          D-       A
4              AL       Clarkland   430 Douglas Mission           A       F
..            ...             ...                   ...         ...     ...
246            WY     Lake Nicole   754 Weaver Turnpike           B      D-
247            WY     Lake Nicole     933 Jennifer Burg           C      A+
248            WY      Martintown        013 Bell Mills          C-       D
249            WY      Port Jason  624 Faulkner Orchard          A-       F
250            WY      Reneeshire      717 Patel Square           B      B+

Category    Services
Subcategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+
..               ...     ...
246                B       D
247               A-       C
248               A-      B-
249               C+      C+
250                D       A

[251 rows x 7 columns]

In [81]:
df_neighbor.set_index(keys='City').head()

Category       State               Street     Culture         Services
Subcategory                               Restaurants Museums   Police Schools
City
Rowlandchester    AK     386 Rebecca Cove          C-      A-       A+       C
Scottstad         AK  082 Leblanc Freeway           D      C-        D      B+
Scottstad         AK     114 Jones Garden          D-      D-        D       D
Stevenshire       AK       238 Andrew Rue          D-       A       A-      A-
Clarkland         AL  430 Douglas Mission           A       F       C+      B+

In [82]:
df_neighbor.set_index(keys=('Culture', 'Museums')).head()

Category           State            City               Street     Culture  \
Subcategory                                                   Restaurants
(Culture, Museums)
A-                    AK  Rowlandchester     386 Rebecca Cove          C-
C-                    AK       Scottstad  082 Leblanc Freeway           D
D-                    AK       Scottstad     114 Jones Garden          D-
A                     AK     Stevenshire       238 Andrew Rue          D-
F                     AL       Clarkland  430 Douglas Mission           A

Category           Services
Subcategory          Police Schools
(Culture, Museums)
A-                       A+       C
C-                        D      B+
D-                        D       D
A                        A-      A-
F                        C+      B+

In [83]:
df_neighbor.set_index(keys=['State', 'City']).head()

Category                           Street     Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City
AK    Rowlandchester     386 Rebecca Cove          C-      A-       A+       C
      Scottstad       082 Leblanc Freeway           D      C-        D      B+
      Scottstad          114 Jones Garden          D-      D-        D       D
      Stevenshire          238 Andrew Rue          D-       A       A-      A-
AL    Clarkland       430 Douglas Mission           A       F       C+      B+

###Exercícios

In [84]:
df_invest = pd.read_csv('investments.csv')
df_invest.head()

                 Name    Market     Status State  Funding Rounds
0            #waywire      News   Acquired    NY               1
1  &TV Communications     Games  Operating    CA               2
2  -R- Ranch and Mine   Tourism  Operating    TX               2
3    004 Technologies  Software  Operating    IL               1
4             1-4 All  Software  Operating    NC               1

In [85]:
df_invest.nunique()

Name              27763
Market              693
Status                3
State                61
Funding Rounds       16
dtype: int64

In [86]:
df_invest = df_invest.set_index(keys=['Status', 'Funding Rounds', 'State']).sort_index()
df_invest.head()

                                                   Name               Market
Status   Funding Rounds State
Acquired 1              AB               Hallpass Media                Games
                        AL                    EnteGreat  Enterprise Software
                        AL     Onward Behavioral Health        Biotechnology
                        AL                      Proxsys        Biotechnology
                        AZ                  Envox Group     Public Relations

In [93]:
df_invest.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 27799 entries, ('Acquired', np.int64(1), 'AB') to ('Operating', np.int64(18), 'CA')
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    27799 non-null  object
 1   Market  27799 non-null  object
dtypes: object(2)
memory usage: 519.3+ KB

In [97]:
df_invest.index.names

FrozenList(['Status', 'Funding Rounds', 'State'])

In [98]:
df_invest.index.get_level_values('Status')

Index(['Acquired', 'Acquired', 'Acquired', 'Acquired', 'Acquired', 'Acquired',
       'Acquired', 'Acquired', 'Acquired', 'Acquired',
       ...
       'Operating', 'Operating', 'Operating', 'Operating', 'Operating',
       'Operating', 'Operating', 'Operating', 'Operating', 'Operating'],
      dtype='object', name='Status', length=27799)