In [1]:
import pandas as pd
import numpy as np

In [10]:
df_employees = pd.read_csv('./employees.csv', parse_dates=['Start Date'])
df_employees

/tmp/ipykernel_19539/1913654741.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_employees = pd.read_csv('./employees.csv', parse_dates=['Start Date'])

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [11]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [12]:
df_employees['Mgmt'].astype(bool) #Transformou a coluna Mgmt de tipo object para bool

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [ ]:
df_employees['Mgmt'] = df_employees['Mgmt'].astype(bool) #Transformando o tipo de dado da coluna Mgmt para booleano

In [15]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [ ]:
df_employees['Salary'].fillna(0).tail() #Transformou os falores NaN da coluna Salary para 0

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         0.0
Name: Salary, dtype: float64

In [17]:
df_employees['Salary'].fillna(0).astype(int).tail()

996      42392
997      96914
998      60500
999     129949
1000         0
Name: Salary, dtype: int64

In [18]:
df_employees['Salary'] = df_employees['Salary'].fillna(0).astype(int)

In [19]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int64(1), object(3)
memory usage: 40.2+ KB

In [ ]:
df_employees.nunique() #Mostr quantos valores únicos o DataFrame possui

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [ ]:
df_employees['Gender'].astype('category') #Transforma o tipo de dado desta coluna para category

0         Male
1         Male
2       Female
3          NaN
4         Male
         ...
996       Male
997       Male
998       Male
999       Male
1000       NaN
Name: Gender, Length: 1001, dtype: category
Categories (2, object): ['Female', 'Male']

In [ ]:
df_employees['Gender'] = df_employees['Gender'].astype('category') #salva a transformação

In [23]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [ ]:
df_employees['Team'].astype('category') #Transforma o tipo de dado desta coluna para category

0          Marketing
1                NaN
2            Finance
3            Finance
4                 IT
            ...
996          Finance
997          Product
998     Business Dev
999            Sales
1000             NaN
Name: Team, Length: 1001, dtype: category
Categories (10, object): ['Business Dev', 'Distribution', 'Engineering', 'Finance', ..., 'Legal', 'Marketing', 'Product', 'Sales']

In [ ]:
df_employees['Team'] = df_employees['Team'].astype('category') #salva a transformação

In [26]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

In [ ]:
df_employees['First Name'] == 'Maria' #Verifica em toda a serie se existe a palavra Maria, caso exista retorna True se não False. Chamado serie booleana percorrendo toda a coluna e classificando True ou False para a operação que foi pedida (== 'Maria')

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [ ]:
df_employees[df_employees['First Name'] == 'Maria'] #utilizando a serie booleana retorna as linhas que deram True

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [ ]:
marias = df_employees['First Name'] == 'Maria' #Este código percorre a serie e os dados que possuem True para a comparação dataframe['coluna] == 'condição' e a linha é adiconada a variável marias
df_employees[marias]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [31]:
df_employees['Team'] != 'Finance'

0        True
1        True
2       False
3       False
4        True
        ...
996     False
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [ ]:
df_employees[df_employees['Team'] != 'Finance'] #utilizando a serie booleana retorna as linhas que deram False

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [34]:
high_earners = df_employees['Salary'] > 100000
high_earners.head()

0    False
1    False
2     True
3     True
4     True
Name: Salary, dtype: bool

In [36]:
df_employees[df_employees['Salary'] > 100000].head()

  First Name  Gender Start Date  Salary   Mgmt          Team
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
9    Frances  Female 2002-08-08  139852   True  Business Dev

In [37]:
is_female = df_employees['Gender'] == 'Female'
is_female

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Gender, Length: 1001, dtype: bool

In [38]:
in_biz_dev = df_employees['Team'] == 'Business Dev'
in_biz_dev

0       False
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998      True
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [ ]:
df_employees[is_female & in_biz_dev].head() #Interceção das duas series utlizando o operador lógico and (&)

   First Name  Gender Start Date  Salary   Mgmt          Team
9     Frances  Female 2002-08-08  139852   True  Business Dev
33       Jean  Female 1993-12-18  119082  False  Business Dev
36     Rachel  Female 2009-02-16  142032  False  Business Dev
38  Stephanie  Female 1986-09-13   36844   True  Business Dev
61     Denise  Female 2001-11-06  106862  False  Business Dev

In [ ]:
is_manager = df_employees['Mgmt']
df_employees[is_female & in_biz_dev & is_manager].head() #Podemos utilizar duas ou mais series utilizando o and

    First Name  Gender Start Date  Salary  Mgmt          Team
9      Frances  Female 2002-08-08  139852  True  Business Dev
38   Stephanie  Female 1986-09-13   36844  True  Business Dev
66       Nancy  Female 2012-12-15  125250  True  Business Dev
92       Linda  Female 2000-05-25  119009  True  Business Dev
111     Bonnie  Female 1999-12-17   42153  True  Business Dev

In [47]:
earning_below_40k = df_employees['Salary'] < 40000
earning_below_40k

0        True
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000     True
Name: Salary, Length: 1001, dtype: bool

In [48]:
started_after_2015 = df_employees['Start Date'] > '2015-01-01'
started_after_2015

0       False
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Start Date, Length: 1001, dtype: bool

In [ ]:
df_employees[earning_below_40k|started_after_2015].head() #Interceção das duas series utlizando o operador lógico or (|), o pandas coloca também as linhas que possuem True e True também

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
7         NaN  Female 2015-07-20   45906   True    Finance
15    Lillian  Female 2016-06-05   59414  False    Product
25        NaN    Male 2012-10-08   37076   True         IT
26      Craig    Male 2000-02-27   37598   True  Marketing

In [ ]:
df_employees[~ (df_employees['Salary'] < 40000)].head() #Interceção da serie utlizando o operador lógico not (~), aqui vou invertido para as linhas que recebem mais de 40000

  First Name  Gender Start Date  Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933   True      NaN
2      Maria  Female        NaT  130590  False  Finance
3      Jerry     NaN 2005-03-04  138705   True  Finance
4      Larry    Male 1998-01-24  101004   True       IT
5     Dennis    Male 1987-04-18  115163  False    Legal

In [50]:
sales = df_employees['Team'] == 'Sales'
legal = df_employees['Team'] == 'Legal'
mktg = df_employees['Team'] == 'Marketing'
df_employees[sales | legal | mktg].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [ ]:
all_star_teams = ['Sales','Legal','Marketing']  #Utilizado quando se deseja fazer muitas comparações com o or
on_all_star_teams = df_employees['Team'].isin(all_star_teams)
df_employees[on_all_star_teams].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [ ]:
between_80K_and_90K = df_employees['Salary'].between(80000, 90000) #Foi usado o método 'between' na coluna Salary para mostras as pessoas que ganham de 80.000 até 90.000. Este resultado é (includente:excludente)
df_employees[between_80K_and_90K].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [ ]:
eighties_folk = df_employees['Start Date'].between(left='1980-01-01', right='1990-01-01') #between pode ser usado para datas também
df_employees[eighties_folk].head()

   First Name  Gender Start Date  Salary   Mgmt     Team
5      Dennis    Male 1987-04-18  115163  False    Legal
6        Ruby  Female 1987-08-17   65476   True  Product
10     Louise  Female 1980-08-12   63241   True      NaN
12    Brandon    Male 1980-12-01  112807   True       HR
17      Shawn    Male 1986-12-07  111737  False  Product

In [ ]:
name_starts_with_r = df_employees['First Name'].between('R', 'S') #between pode ser usado para strings também
df_employees[name_starts_with_r].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
6        Ruby  Female 1987-08-17   65476   True       Product
36     Rachel  Female 2009-02-16  142032  False  Business Dev
45      Roger    Male 1980-04-17   88010   True         Sales
67     Rachel  Female 1999-08-16   51178   True       Finance
78      Robin  Female 1983-06-04  114797   True         Sales